wix/Build.OpenJDK10.jdk_x64_windows_hotspot.cmd
wix/Build.OpenJDK10.jdk_x64_windows_openj9.cmd
wix/Build.OpenJDK11.jdk_x64_windows_hotspot.cmd
wix/Build.OpenJDK11.jdk_x64_windows_openj9.cmd
wix/Build.OpenJDK8.jdk_x64_windows_hotspot.cmd
wix/Build.OpenJDK8.jdk_x64_windows_openj9.cmd
wix/BuildSetupTranslationTransform.cmd
wix/Includes/OpenJDK.Variables.wxi
wix/Main.hotspot.wxs
wix/Main.openj9.wxs
wix/readme.TXT

https://github.com/AdoptOpenJDK/openjdk-installer/issues/12 an some other important fixes.

MSI installers remember path between versions, but should not

---

wix/Main.openj9.wxs
wix/Resources/license-OpenJ9.en-us.rtf

closes: https://github.com/AdoptOpenJDK/openjdk-installer/issues/40

license: use openj9 license

---

wix/Main.hotspot.wxs
wix/Main.openj9.wxs

- Put jdk/bin at beginning of PATH
- Override JAVA_HOME or JRE_HOME .. dont append to it

Fix environment variables

---

pkgbuild/pkgbuild.sh

update pkg build to include CommandLine for JRE's

---

wix/Build.OpenJDK_generic.cmd
wix/Main.hotspot.wxs
wix/Main.openj9.wxs

closes: https://github.com/AdoptOpenJDK/openjdk-installer/issues/66

fix JRE_HOME and re-enable testing

---

wix/Build.OpenJDK_generic.cmd
wix/BuildSetupTranslationTransform.cmd

skip signing if no certificate given
use signtool from the configured Windows Kits version

add opt SKIP_MSI_VALIDATION to skip MSI validation

---

wix/Lang/LanguageList.config

blank lines are not a problem.

enhanced comment on config file

---

wix/Build.OpenJDK_generic.cmd
wix/Includes/OpenJDK.Variables.wxi
wix/Main.hotspot.wxs
wix/Main.openj9.wxs

and rename some variables in cmd
closes: #58

add hostpot or openj9 to install folder and reg key #58

---

wix/Build.OpenJDK_generic.cmd
wix/Lang/OpenJDK.Base.de-de.wxl
wix/Lang/OpenJDK.Base.en-us.wxl
wix/Lang/OpenJDK.Base.es-es.wxl
wix/Lang/OpenJDK.Base.fr-fr.wxl
wix/Lang/OpenJDK.Base.ja-jp.wxl
wix/Lang/OpenJDK.Base.zh-cn.wxl
wix/Lang/OpenJDK.Base.zh-tw.wxl
wix/Main.hotspot.wxs
wix/Main.openj9.wxs
wix/README.md
wix/getGuid.ps1

add UPGRADE_CODE_SEED ( optionnal )
add new powershell script for generate GUID PRODUCT_UPGRADE_COD based on version string
add localized message for downgrade refused
add reinstall sample on README
add notes on README for msi upgrade (miss)capability
closes: https://github.com/AdoptOpenJDK/openjdk-installer/issues/59

[MSI] Set option for keeping same UpgradeCode #59

---

wix/Build.OpenJDK_generic.cmd

to support Semver introduce by 660fc4bd3e1bde8514d5a4ab1ac8a09e5d25c69b

[WIP] add new directory layout without build number

---

wix/Lang/OpenJDK.Base.de-de.wxl
wix/Lang/OpenJDK.Base.en-us.wxl
wix/Lang/OpenJDK.Base.es-es.wxl
wix/Lang/OpenJDK.Base.fr-fr.wxl
wix/Lang/OpenJDK.Base.ja-jp.wxl
wix/Lang/OpenJDK.Base.zh-cn.wxl
wix/Lang/OpenJDK.Base.zh-tw.wxl
wix/Lang/OpenJDK.hotspot.de-de.wxl
wix/Lang/OpenJDK.hotspot.en-us.wxl
wix/Lang/OpenJDK.hotspot.es-es.wxl
wix/Lang/OpenJDK.hotspot.fr-fr.wxl
wix/Lang/OpenJDK.hotspot.ja-jp.wxl
wix/Lang/OpenJDK.hotspot.zh-cn.wxl
wix/Lang/OpenJDK.hotspot.zh-tw.wxl
wix/Lang/OpenJDK.openj9.de-de.wxl
wix/Lang/OpenJDK.openj9.en-us.wxl
wix/Lang/OpenJDK.openj9.es-es.wxl
wix/Lang/OpenJDK.openj9.fr-fr.wxl
wix/Lang/OpenJDK.openj9.ja-jp.wxl
wix/Lang/OpenJDK.openj9.zh-cn.wxl
wix/Lang/OpenJDK.openj9.zh-tw.wxl
wix/Main.hotspot.wxs
wix/Main.openj9.wxs

There was a mix of tabs and spaces in some files. I have changed
files to be consistent with either all spaces or all tabs. I based
the change on what was more common in the individual file.
Signed-off-by: Charlie Gracie <charlie.gracie@gmail.com>

Fix tabs vs spaces

---

wix/Includes/OpenJDK.Variables.wxi
wix/Lang/OpenJDK.Base.de-de.wxl
wix/Lang/OpenJDK.Base.en-us.wxl
wix/Lang/OpenJDK.Base.es-es.wxl
wix/Lang/OpenJDK.Base.fr-fr.wxl
wix/Lang/OpenJDK.Base.ja-jp.wxl
wix/Lang/OpenJDK.Base.zh-cn.wxl
wix/Lang/OpenJDK.Base.zh-tw.wxl
wix/Main.hotspot.wxs
wix/Main.openj9.wxs
wix/README.md

Please wait some result from standalone_create_installer_windows job before merge
I will run it now
closes: #64

Provide Oracle JDK compatible registry keys (Windows) #64

---

wix/Lang/OpenJDK.Base.es-es.wxl

Reverts AdoptOpenJDK/openjdk-installer#85

Revert "Updated Spanish translation"

---

wix/Lang/OpenJDK.Base.es-es.wxl

New take on #85. Thanks @douph1 for the French translation hint.

Updated Spanish translation

---

wix/Build.OpenJDK_generic.cmd
wix/BuildSetupTranslationTransform.cmd
wix/Lang/OpenJDK.Base.de-de.wxl
wix/Lang/OpenJDK.Base.en-us.wxl
wix/Lang/OpenJDK.Base.es-es.wxl
wix/Lang/OpenJDK.Base.fr-fr.wxl
wix/Lang/OpenJDK.Base.ja-jp.wxl
wix/Lang/OpenJDK.Base.zh-cn.wxl
wix/Lang/OpenJDK.Base.zh-tw.wxl
wix/Main.hotspot.wxs
wix/Main.openj9.wxs
wix/README.md
wix/Resources/heat.icedteaweb.xslt

Signed-off-by: Charlie Gracie <charlie.gracie@gmail.com>

Add IcedTea-Web as an optional part of the install

---

wix/Build.OpenJDK_generic.cmd
wix/BuildSetupTranslationTransform.cmd
wix/Main.hotspot.wxs
wix/Main.openj9.wxs

waiting CI job result  to approve and testing artefacts
Expecting ITW no present anymore on MSI x86-32 but always present on MIS x64

[WIP] disable ITW for x86_32

---

wix/Main.hotspot.wxs
wix/Main.openj9.wxs

fix for https://github.com/AdoptOpenJDK/openjdk-installer/issues/119

Fix jar Content Type

---

wix/Main.hotspot.wxs
wix/Main.openj9.wxs

fix for https://github.com/AdoptOpenJDK/openjdk-installer/issues/123

fix java version compare

---

wix/Includes/OpenJDK.Variables.wxi

fix for https://github.com/AdoptOpenJDK/openjdk-installer/pull/139
@gdams can you merge please

fix folder path separator (unix > windows)

---

wix/Includes/OpenJDK.Variables.wxi

fix for build failed after PR for #137

fix build failed for JDK since last change about RuntimeLib jvm.dll

---

wix/Build.OpenJDK_generic.cmd

Intended to help understand https://github.com/AdoptOpenJDK/openjdk-installer/issues/157

List directories in case of jre/jdk dir not found

---

linux/README.md
linux/deb/build.gradle
linux/rpm/build.gradle

Ubuntu: Drop cosmic, add eoan.
OpenSUSE: Add 15.1

Update supported distributions

---

pkgbuild/pkgbuild.sh

Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>

Reenable notarize

---

linux/standalone_create_installer_linux.sh

Go back to old filename scheme for download URLs

---

linux/build.gradle

Within ext, hasProperty() does not operate on the project but on ext itself.
Fixes #224.

Fix property resolution

---

linux/build.gradle
linux/buildSrc/src/main/java/net/adoptopenjdk/installer/BuildRpmPackage.java

Remove symlink to Japanese man pages in RPMs

---

linux/create_installer_linux.sh

This allows the installers to be built but not uploaded to artifactory (by forcing `GRADLE_TASK=build`) if artifactory credentials have not been supplied, for the situation where someone outside adoptopenjdk is running our pipelines (since this will currently fail in that situation and not allow the installers to be archived)
We should possibly also look at making the artifactory server name a parameter along with the username and password to incfrease flexibility
Signed-off-by: Stewart Addison <sxa@uk.ibm.com>

Allow installers to build in pipelines without artifactory

---

wix/Build.OpenJDK_generic.cmd

PR 261 accidentally removed this. Adding it back in.
Signed-off-by: Adam Farley <adfarley@redhat.com>

Add missing "jdk-" to zip path

---

wix/Build.OpenJDK_generic.cmd
wix/Main.hotspot.wxs
wix/Main.openj9.wxs
wix/README.md
wix/SourceDir/CreateSourceFolder.AdoptOpenJDK.ps1

fixes: https://github.com/AdoptOpenJDK/openjdk-installer/issues/276
Test build: https://ci.adoptopenjdk.net/view/work-in-progress/job/create_installer_windows_aarch64/10/
Confirmed to be working on Surface Pro X

add aarch64 windows installer support

---

wix/Build.OpenJDK_generic.cmd
wix/Lang/OpenJDK.dragonwell.de-de.wxl
wix/Lang/OpenJDK.dragonwell.en-us.wxl
wix/Lang/OpenJDK.dragonwell.es-es.wxl
wix/Lang/OpenJDK.dragonwell.fr-fr.wxl
wix/Lang/OpenJDK.dragonwell.ja-jp.wxl
wix/Lang/OpenJDK.dragonwell.zh-cn.wxl
wix/Lang/OpenJDK.dragonwell.zh-tw.wxl
wix/Main.dragonwell.wxs
wix/README.md
wix/SourceDir/CreateSourceFolder.AdoptOpenJDK.ps1
wix/SourceDir/CreateSourceFolder.OpenJDK11.ps1
wix/SourceDir/CreateSourceFolder.OpenJDK8.ps1

Issue: https://github.com/AdoptOpenJDK/openjdk-installer/issues/279

Add Dragonwell support in regex

---

wix/InstallerChangelog.md
wix/fixChangelog.sh

Changelog for Windows Installer

---

linux/standalone_create_installer_linux.sh

Because https://github.com/AdoptOpenJDK/openjdk-build/issues/2524.

Deal with missing U in file names for 16

---

linux/create_installer_linux.sh

Follow up to 19208d91ad903d463258997ca039a988928a6e88. Turned out there are more Us.

Fix additional U problems

---

linux/standalone_create_installer_linux.sh

Signed-off-by: Andrew Leonard <anleonar@redhat.com>

Enable standalone_create_installer_linux to find both U and non-U suffix tarballs

---

README.md

Signed-off-by: Andrew Leonard <anleonar@redhat.com>

Update README on creating Release Linux installers

---

linuxNew/jdk/redhat/src/main/packaging/openj9/11/README.md
linuxNew/jdk/redhat/src/main/packaging/openj9/11/java-11-openj9.spec
linuxNew/jdk/redhat/src/main/packaging/openj9/8/README.md
linuxNew/jdk/redhat/src/main/packaging/openj9/8/java-1.8.0-openj9.spec
linuxNew/jdk/redhat/src/main/packaging/openj9/run_build.sh

@AdamBrousseau @smlambert FYI.

Openj9 spec addition for linuxNew

---

codesign/eclipse-codesign.sh

and remove curl progress
fix for #323

EF signing: make curl failing if http status code error

---

.github/workflows/linux.yml

Was accidentally left out of the original import of the new Linux package sources. It already includes a check for #338.

Add workflow to check Linux packages

---

wix/SourceDir/CreateSourceFolder.AdoptOpenJDK.ps1
wix/SourceDir/CreateSourceFolder.OpenJDK11.ps1

Because in Jenkins the script fails but silently.

Add debug logging to script for windows installer

---

wix/SourceDir/CreateSourceFolder.AdoptOpenJDK.ps1
wix/SourceDir/CreateSourceFolder.OpenJDK11.ps1

- Add debug logging to script for windows installer
- More Debug

add debug to windows

---

wix/SourceDir/CreateSourceFolder.AdoptOpenJDK.ps1
wix/SourceDir/CreateSourceFolder.OpenJDK11.ps1

- revert some debug logging
- revert some debug logging

rollback debug

---

.github/workflows/linux.yml
linuxNew/Jenkinsfile

This PR archives the generated deb/rpm files in jenkins.

Add archive artefact stage to linux new installers

---

linuxNew/jdk/debian/src/main/packaging/temurin/11/debian/changelog
linuxNew/jdk/debian/src/main/packaging/temurin/11/debian/rules
linuxNew/jdk/debian/src/main/packaging/temurin/17/debian/changelog
linuxNew/jdk/debian/src/main/packaging/temurin/17/debian/rules
linuxNew/jdk/debian/src/main/packaging/temurin/8/debian/changelog
linuxNew/jdk/debian/src/main/packaging/temurin/8/debian/rules
linuxNew/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec
linuxNew/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
linuxNew/jdk/redhat/src/main/packaging/temurin/8/temurin-8-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/11/temurin-11-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/8/temurin-8-jdk.spec

Update version and rename debian installer

---

linuxNew/Jenkinsfile

Do not fail jenkins if test fails so rpm can be archived

---

linuxNew/Jenkinsfile

Tests should be green as non x86_64 arch tests disabled

---

linuxNew/jdk/suse/build.gradle
linuxNew/jdk/suse/src/packageTest/java/packaging/ZypperOperationsTest.java

fixes: https://github.com/adoptium/installer/issues/385
Tests all passed in https://ci.adoptopenjdk.net/job/gdams-packages-linux-pipeline/29/

skip gpg signature checks on opensuse

---

linuxNew/Jenkinsfile

Upload RPM to artifactory

---

linuxNew/jdk/redhat/src/main/packaging/Dockerfile
linuxNew/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec
linuxNew/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
linuxNew/jdk/redhat/src/main/packaging/temurin/8/temurin-8-jdk.spec
linuxNew/jdk/suse/src/main/packaging/Dockerfile
linuxNew/jdk/suse/src/main/packaging/temurin/11/temurin-11-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/8/temurin-8-jdk.spec

Support aarch64

---

linuxNew/Jenkinsfile
linuxNew/jdk/redhat/src/main/packaging/Dockerfile
linuxNew/jdk/redhat/src/main/packaging/temurin/8/temurin-8-jdk.spec
linuxNew/jdk/suse/src/main/packaging/Dockerfile
linuxNew/jdk/suse/src/main/packaging/temurin/11/temurin-11-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/8/temurin-8-jdk.spec

Close #390 
Temporary solution for https://github.com/adoptium/temurin-build/issues/2795

Upload arm32 package to jfrog artifactory

---

linuxNew/Jenkinsfile

enable all versions or specific version

Clean up Jenkinsfile

---

linuxNew/Jenkinsfile
linuxNew/jdk/redhat/src/packageTest/java/packaging/RedHatFlavoursWithDnf.java

Fedora: Drop 33, add 34,35. Centos: drop 7

---

linuxNew/Jenkinsfile

Only enable non-x64 packaging stage to debian distr

---

linuxNew/jdk/redhat/src/packageTest/java/packaging/RedHatFlavoursWithDnf.java
linuxNew/jdk/redhat/src/packageTest/java/packaging/RedHatFlavoursWithYum.java
linuxNew/jdk/suse/src/packageTest/java/packaging/SuseFlavours.java

Add the tests for rhel 7, 8 and suse 15.3

---

.github/workflows/linux.yml
linuxNew/Jenkinsfile
linuxNew/jdk/redhat/src/packageTest/java/packaging/RedHatFlavoursWithDnf.java
linuxNew/jdk/suse/src/packageTest/java/packaging/SuseFlavours.java

closes: https://github.com/adoptium/installer/issues/420

linux: add Sles 12 and 15 support and switch centos8 to rocky8

---

linuxNew/jdk/debian/src/main/packaging/temurin/8/debian/changelog
linuxNew/jdk/debian/src/main/packaging/temurin/8/debian/rules
linuxNew/jdk/redhat/src/main/packaging/temurin/8/temurin-8-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/8/temurin-8-jdk.spec

Update packaging for jdk8u322-b06

---

linuxNew/jdk/debian/src/main/packaging/temurin/11/debian/changelog
linuxNew/jdk/debian/src/main/packaging/temurin/11/debian/rules
linuxNew/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/11/temurin-11-jdk.spec

Updated the jdk11 installers to use jdk-11.0.15+10

Update installers for jdk-11.0.15+10

---

linuxNew/jdk/debian/src/main/packaging/temurin/17/debian/changelog
linuxNew/jdk/debian/src/main/packaging/temurin/17/debian/rules
linuxNew/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec

Updated the jdk17 installers to use jdk-17.0.3+7

Update installers for jdk-17.0.3+7

---

linuxNew/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/11/temurin-11-jdk.spec

Update global version

---

linuxNew/jdk/debian/src/main/packaging/temurin/18/debian/changelog
linuxNew/jdk/debian/src/main/packaging/temurin/18/debian/rules
linuxNew/jdk/redhat/src/main/packaging/temurin/18/temurin-18-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/18/temurin-18-jdk.spec

Updated the jdk18 installer files to use 18.0.1+10

Update installer files for jdk18

---

linuxNew/jdk/debian/src/main/packaging/temurin/8/debian/changelog
linuxNew/jdk/debian/src/main/packaging/temurin/8/debian/rules
linuxNew/jdk/redhat/src/main/packaging/temurin/8/temurin-8-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/8/temurin-8-jdk.spec

Updated the installer files for jdk8 to use the 8u332-b09 tag

Update jdk8 installers to jdk8-8u332-b09

---

linux/jdk/debian/src/main/packaging/temurin/17/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/17/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec

Update jdk17 installers to jdk-17.0.4+8

---

linux/jdk/debian/src/main/packaging/temurin/11/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/11/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/11/temurin-11-jdk.spec

Update installers for jdk11 to jdk-11.0.16+8

---

linux/jdk/debian/src/main/packaging/temurin/18/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/18/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/18/temurin-18-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/18/temurin-18-jdk.spec

Update jdk18 installers to jdk-18.0.2+9

---

linux/jdk/debian/src/main/packaging/temurin/18/debian/rules

Update jdk18 s390x arm32 debain installers to jdk-18.0.2+9

---

linux/jdk/suse/src/main/packaging/temurin/18/temurin-18-jdk.spec

Update jdk18 suse to 18.0.2+9

---

README.md

README: change title

---

linux/jdk/debian/src/main/packaging/temurin/11/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/11/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/11/temurin-11-jdk.spec

Update jdk11 to jdk11.0.16.1+1

---

linux/jdk/debian/src/main/packaging/temurin/17/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/17/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec

Update jdk17 to jdk-17.0.4.1+1

---

linux/jdk/debian/src/main/packaging/temurin/18/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/18/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/18/temurin-18-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/18/temurin-18-jdk.spec

Update jdk18 to jdk-18.0.2.1+1 (#520)

---

wix/Main.wxs.template

This PR is backport of https://github.com/AdoptOpenJDK/IcedTea-Web/pull/384
Signed-off-by: Pasam Soujanya psoujany@in.ibm.com

Adding "application/x-java-jnlp-file" mimetype association to MSI

---

README.md
linux/jdk/debian/src/main/packaging/temurin/8/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/8/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/8/temurin-8-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/8/temurin-8-jdk.spec

shipped:
x64 linux
ppc64le
aarch64
arm32

release: jdk8u352-b08

---

wix/Build.OpenJDK_generic.cmd
wix/README.md

The links are outdated so should be updated

Windows MSI update product URLs

---

linux/jdk/debian/src/main/packaging/temurin/19/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/19/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/19/temurin-19-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/19/temurin-19-jdk.spec

shipped
x64 linux
aarch64
ppc64le
arm32
s390x

release: jdk19.0.1+10

---

linux/Jenkinsfile

- old solution loops thro each char in string which makes no label on the node available

fix: only have one arch defined in Deb, make sure the node label correct

---

linux/jdk/debian/src/main/packaging/temurin/11/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/11/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/11/temurin-11-jdk.spec

x64 shipped
aarch64 shipped
ppc64le shipped
arm32 shipped
s390 shipped

release: jdk11.0.17+8

---

linux/jdk/debian/src/main/packaging/temurin/17/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/17/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec

shipped:
x64 linux
aarch64 linux
ppc64le
arm32
s390x

release: jdk17.0.5+8

---

linux/jdk/alpine/src/main/packaging/temurin/17/APKBUILD
linux/jdk/debian/src/main/packaging/temurin/17/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/17/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec

shipped:
x64 linux
aarch64 linux
ppc64le
arm32
s390x
alpine

release: jdk17.0.6+10

---

linux/jdk/alpine/src/main/packaging/temurin/11/APKBUILD
linux/jdk/debian/src/main/packaging/temurin/11/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/11/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/11/temurin-11-jdk.spec

shipped:
x64 linux
aarch64 linux
ppc64le
arm32
s390x
alpine

release: jdk11.0.18+10

---

linux/jdk/alpine/src/main/packaging/temurin/8/APKBUILD
linux/jdk/debian/src/main/packaging/temurin/8/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/8/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/8/temurin-8-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/8/temurin-8-jdk.spec

shipped:
x64 linux
aarch64 linux
ppc64le
arm32
alpine

release: jdk8u362-b09

---

README.md

Linked to https://github.com/adoptium/infrastructure/issues/2932

Change references of ci.adoptopenjdk.net to ci.adoptium.net

---

linux/jre/redhat/src/main/packaging/temurin/11/temurin-11-jre.spec
linux/jre/redhat/src/main/packaging/temurin/17/temurin-17-jre.spec
linux/jre/redhat/src/main/packaging/temurin/19/temurin-19-jre.spec
linux/jre/redhat/src/main/packaging/temurin/20/temurin-20-jre.spec
linux/jre/redhat/src/main/packaging/temurin/8/temurin-8-jre.spec
linux/jre/suse/src/main/packaging/temurin/11/temurin-11-jre.spec
linux/jre/suse/src/main/packaging/temurin/17/temurin-17-jre.spec
linux/jre/suse/src/main/packaging/temurin/19/temurin-19-jre.spec
linux/jre/suse/src/main/packaging/temurin/20/temurin-20-jre.spec
linux/jre/suse/src/main/packaging/temurin/8/temurin-8-jre.spec

fixes https://github.com/adoptium/installer/issues/632
This PR needs merging ahead of the release so it's fixed for the next round of installers that we release

fix broken preuninstall script for JREs

---

.github/workflows/linux.yml

Currently the matrix is failing to generate on push commands

fix failing generate matrix job on push

---

linux/jdk/redhat/src/main/packaging/build.sh
linux/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec
linux/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
linux/jdk/redhat/src/main/packaging/temurin/20/temurin-20-jdk.spec
linux/jdk/redhat/src/main/packaging/temurin/8/temurin-8-jdk.spec
linux/jdk/suse/src/main/packaging/build.sh
linux/jdk/suse/src/main/packaging/temurin/11/temurin-11-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/20/temurin-20-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/8/temurin-8-jdk.spec
linux/jre/redhat/src/main/packaging/build.sh
linux/jre/redhat/src/main/packaging/temurin/11/temurin-11-jre.spec
linux/jre/redhat/src/main/packaging/temurin/17/temurin-17-jre.spec
linux/jre/redhat/src/main/packaging/temurin/20/temurin-20-jre.spec
linux/jre/redhat/src/main/packaging/temurin/8/temurin-8-jre.spec
linux/jre/suse/src/main/packaging/build.sh
linux/jre/suse/src/main/packaging/temurin/11/temurin-11-jre.spec
linux/jre/suse/src/main/packaging/temurin/17/temurin-17-jre.spec
linux/jre/suse/src/main/packaging/temurin/20/temurin-20-jre.spec
linux/jre/suse/src/main/packaging/temurin/8/temurin-8-jre.spec

This allows us to automatically parse the list of arches to build from the specfile rather than writing if statements

feat: switch spec files to define ExclusiveArch

---

linux/jre/alpine/src/main/packaging/Dockerfile

Fixes Issue #663 
This PR aligns the JDK/JRE dockerfiles, in regard the adding of the GPG signing key.

Fix jre alpine dockerfile

---

linux/Jenkinsfile

Fix Alpine Artifact Upload Pattern Matching To Be More Precise

---

linux/jdk/alpine/src/main/packaging/temurin/8/APKBUILD
linux/jdk/debian/src/main/packaging/temurin/8/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/8/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/8/temurin-8-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/8/temurin-8-jdk.spec
linux/jre/alpine/src/main/packaging/temurin/8/APKBUILD
linux/jre/debian/src/main/packaging/temurin/8/debian/changelog
linux/jre/debian/src/main/packaging/temurin/8/debian/rules
linux/jre/redhat/src/main/packaging/temurin/8/temurin-8-jre.spec
linux/jre/suse/src/main/packaging/temurin/8/temurin-8-jre.spec

shipped:
x64 linux
aarch64 linux
ppc64le
arm32
alpine

release: jdk8u372-b07

---

linux/Jenkinsfile
linux/README.md
linux/jdk/redhat/src/packageTest/java/packaging/RedHatFlavoursWithDnf.java
linux/jre/redhat/src/packageTest/java/packaging/RedHatFlavoursWithDnf.java

Ref: https://github.com/adoptium/adoptium/issues/233

feat: add support for fedora38 installer

---

linux/jdk/suse/src/packageTest/java/packaging/SuseFlavours.java
linux/jre/suse/src/packageTest/java/packaging/SuseFlavours.java

Support sles12 tests

---

linux/jdk/alpine/src/main/packaging/temurin/20/APKBUILD
linux/jdk/debian/src/main/packaging/temurin/20/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/20/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/20/temurin-20-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/20/temurin-20-jdk.spec
linux/jre/alpine/src/main/packaging/temurin/20/APKBUILD
linux/jre/debian/src/main/packaging/temurin/20/debian/changelog
linux/jre/debian/src/main/packaging/temurin/20/debian/rules
linux/jre/redhat/src/main/packaging/temurin/20/temurin-20-jre.spec
linux/jre/suse/src/main/packaging/temurin/20/temurin-20-jre.spec

Styled after the [April PR](https://github.com/adoptium/installer/pull/662/files)

Installer updates for JDK20 for July 2023 release

---

linux/jdk/debian/src/main/packaging/microsoft/11/debian/changelog
linux/jdk/debian/src/main/packaging/microsoft/11/debian/rules
linux/jdk/debian/src/main/packaging/microsoft/17/debian/changelog
linux/jdk/debian/src/main/packaging/microsoft/17/debian/rules

Waiting for verification that libfreetype 'issue' is resolved, do not merge yet

MSFT: Removed bash code that removed ca-certificates, updated changelog

---

linux/Jenkinsfile
linux/jre/redhat/src/main/packaging/temurin/8/temurin-8-jre.spec
linux/jre/suse/src/main/packaging/temurin/8/temurin-8-jre.spec

Add additional armv7hl parameter as workaround for arm32, fix jre dates

Add additional armv7hl parameter as workaround for arm32, fix arm32 jre dates

---

.github/workflows/cacert-publish.yml
linux/Jenkinsfile

I missed the quotes around the `rt u` command

fix jenkins rt command

---

.github/workflows/cacert-publish.yml

Use action's immutable hashcode rather than mutable tag.

Depend on jfrog action hash

---

linux/jre/redhat/src/main/packaging/temurin/11/temurin-11-jre.spec
linux/jre/suse/src/main/packaging/temurin/11/temurin-11-jre.spec

fixes: https://github.com/adoptium/installer/issues/749

fix malformed update-alternatives command

---

linux/jdk/alpine/src/main/packaging/temurin/21/APKBUILD
linux/jdk/debian/src/main/packaging/temurin/21/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/21/debian/rules
linux/jdk/redhat/src/main/packaging/build.sh
linux/jdk/redhat/src/main/packaging/temurin/21/temurin-21-jdk.spec
linux/jdk/suse/src/main/packaging/build.sh
linux/jdk/suse/src/main/packaging/temurin/21/temurin-21-jdk.spec
linux/jre/alpine/src/main/packaging/temurin/21/APKBUILD
linux/jre/debian/src/main/packaging/temurin/21/debian/changelog
linux/jre/debian/src/main/packaging/temurin/21/debian/rules
linux/jre/redhat/src/main/packaging/build.sh
linux/jre/redhat/src/main/packaging/temurin/21/temurin-21-jre.spec
linux/jre/suse/src/main/packaging/build.sh
linux/jre/suse/src/main/packaging/temurin/21/temurin-21-jre.spec

jdk-21 Oct CPU installers

---

linux/jdk/alpine/src/main/packaging/temurin/17/APKBUILD
linux/jdk/debian/src/main/packaging/temurin/17/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/17/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec
linux/jre/alpine/src/main/packaging/temurin/17/APKBUILD
linux/jre/debian/src/main/packaging/temurin/17/debian/changelog
linux/jre/debian/src/main/packaging/temurin/17/debian/rules
linux/jre/redhat/src/main/packaging/temurin/17/temurin-17-jre.spec
linux/jre/suse/src/main/packaging/temurin/17/temurin-17-jre.spec

jdk17 Oct CPU 2023 installer

---

linux/jdk/alpine/src/main/packaging/temurin/11/APKBUILD
linux/jdk/debian/src/main/packaging/temurin/11/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/11/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/11/temurin-11-jdk.spec
linux/jre/debian/src/main/packaging/temurin/11/debian/changelog
linux/jre/debian/src/main/packaging/temurin/11/debian/rules
linux/jre/redhat/src/main/packaging/temurin/11/temurin-11-jre.spec
linux/jre/suse/src/main/packaging/temurin/11/temurin-11-jre.spec

Signed-off-by: Sophia Guo [sophia.gwf@gmail.com](mailto:sophia.gwf@gmail.com)

jdk11 Oct PSU installers

---

linux/jdk/alpine/src/main/packaging/temurin/8/APKBUILD
linux/jdk/debian/src/main/packaging/temurin/8/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/8/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/8/temurin-8-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/8/temurin-8-jdk.spec
linux/jre/alpine/src/main/packaging/temurin/8/APKBUILD
linux/jre/debian/src/main/packaging/temurin/8/debian/changelog
linux/jre/debian/src/main/packaging/temurin/8/debian/rules
linux/jre/redhat/src/main/packaging/temurin/8/temurin-8-jre.spec
linux/jre/suse/src/main/packaging/temurin/8/temurin-8-jre.spec

jdk8 Oct PSU installers

---

linux/jdk/debian/src/main/packaging/temurin/8/debian/rules
linux/jre/debian/src/main/packaging/temurin/8/debian/rules

Update jdk8 arm october CPU infor

---

linux/Jenkinsfile
linux/README.md
linux/jdk/redhat/src/packageTest/java/packaging/RedHatFlavoursWithDnf.java
linux/jre/redhat/src/packageTest/java/packaging/RedHatFlavoursWithDnf.java

feat: fedora 39 installers

---

linux/jdk/alpine/src/main/packaging/temurin/17/APKBUILD
linux/jdk/debian/src/main/packaging/temurin/17/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/17/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec
linux/jre/alpine/src/main/packaging/temurin/17/APKBUILD
linux/jre/debian/src/main/packaging/temurin/17/debian/changelog
linux/jre/debian/src/main/packaging/temurin/17/debian/rules
linux/jre/redhat/src/main/packaging/temurin/17/temurin-17-jre.spec
linux/jre/suse/src/main/packaging/temurin/17/temurin-17-jre.spec

To be merged after jdk17 s390x and arm32 linux platforms are released

Update JDK17 installers for Jan 2024 release

---

README.md
linux/Jenkinsfile

Fixes #809
Ensure JDK version is propogated to lower functions for Debian, this should prevent recurrence of the upload to a -${VERSION} folder in artifactory.

Fix Debian Uploads When Dist = All

---

linux/Jenkinsfile

Fix missing single quotes for Alpine version compare.

Syntax Fix For Version Compare.

---

.github/workflows/wix.yml

Some minor refactoring. Removes all deprecation warnings we're currently seeing in the workflow runs

minor improvements to wix.yml workflow

---

wix/Jenkinsfile

Created a Jenkinsfile rather than having a random job declared in the UI

create jenkinsfile for wix installer builds

---

pkgbuild/Jenkinsfile

Created a Jenkinsfile rather than having a random job declared in the UI
Can be seen running successfully at https://ci.adoptium.net/job/build-scripts/job/release/job/create_installer_mac/

add macOS Jenkinsfile

---

.github/workflows/semgrep_diff.yml

Add new github action to perform semgrep differential scanning

Add new github action to perform semgrep differential scanning

---

linux/jdk/alpine/src/main/packaging/Dockerfile
linux/jdk/alpine/src/packageTest/java/packaging/AlpineFlavours.java
linux/jre/alpine/src/main/packaging/Dockerfile
linux/jre/alpine/src/packageTest/java/packaging/AlpineFlavours.java

Fixes:
```bash
>>> temurin-21: Updating the workspace/x86_64 repository index...
ERROR: temurin-21-21.0.3_p9-r1.apk: UNTRUSTED signature
ERROR: temurin-21-jre-21.0.3_p9-r1.apk: UNTRUSTED signature
>>> ERROR: temurin-21: Failed to create index
>>> temurin-21: Uninstalling dependencies...
ERROR: No such package: .makedepends-temurin-21
```

fix failing Alpine Linux builds

---

linux/jre/debian/src/main/packaging/temurin/17/debian/rules

July CPU : Fix Checksum For Debian JRE 17 Riscv

July CPU : Fix Checksum For Debian JRE 17 Riscv

---

linux/Jenkinsfile

Add rawhide to linux RPM package repository.
See #1046

Add Fedora Rawhide Distro.

---

linux/Jenkinsfile
linux/jdk/redhat/src/packageTest/java/packaging/RedHatFlavoursWithDnf.java
linux/jre/redhat/src/packageTest/java/packaging/RedHatFlavoursWithDnf.java
linux_new/Jenkinsfile
linux_new/jdk/rhel/src/packageTest/java/packaging/RedHatFlavoursWithDnf.java
linux_new/jre/rhel/src/packageTest/java/packaging/RedHatFlavoursWithDnf.java

Add CentOS (Stream) 9 and CentOS (Stream) 10 to build matrix

---

linux/Jenkinsfile
linux_new/Jenkinsfile

Fixes #1189 
Update jenkinsfile to upload packages to artifactory for RHEL10 distribution.

Add RHEL10 distro.
