wix/Lang/OpenJDK.Base.de-de.wxl
wix/Lang/OpenJDK.Base.en-us.wxl
wix/Lang/OpenJDK.Base.es-es.wxl
wix/Lang/OpenJDK.Base.fr-fr.wxl
wix/Lang/OpenJDK.Base.ja-jp.wxl
wix/Lang/OpenJDK.Base.zh-cn.wxl
wix/Lang/OpenJDK.Base.zh-tw.wxl
wix/Main.hotspot.wxs
wix/Main.openj9.wxs
wix/README.md
wix/SourceDir/CreateSourceFolder.OpenJDK11.ps1
wix/SourceDir/CreateSourceFolder.OpenJDK8.ps1

Adding registry keys to map .jar extension with javaw.exe -jar
closes: https://github.com/AdoptOpenJDK/openjdk-installer/issues/32

Double-click on JAR doesn't launch the application #32

---

wix/Build.OpenJDK_generic.cmd

Checking the msi installer on Windows 10 - installs OK but I get a strange file name presented rather than the real msi installer file name. This changes the name to just present the Vendor name (`AdoptOpenJDK`) which appears to be standard behavior.

add description

---

wix/Build.OpenJDK_generic.cmd

Currently on jdk11 and 12 we are bundling the JDK into the JRE installer. This is a bug.

add jre sourceDir

---

linux/deb/config/jdk-10-hotspot/dependencies.txt
linux/deb/config/jdk-10-openj9/dependencies.txt
linux/deb/config/jdk-11-hotspot/dependencies.txt
linux/deb/config/jdk-11-openj9/dependencies.txt
linux/deb/config/jdk-12-hotspot/dependencies.txt
linux/deb/config/jdk-12-openj9/dependencies.txt
linux/deb/config/jdk-8-hotspot/dependencies.txt
linux/deb/config/jdk-8-openj9/dependencies.txt
linux/deb/config/jdk-9-hotspot/dependencies.txt
linux/deb/config/jdk-9-openj9/dependencies.txt

libfreetype6-dev is a development dependency which would only be used, if AdoptOpenJDK compiles something to link to it either during or after package installation. But this does not seem to be the case.

Only depend on libfreetype6 instead of libfreetype6-dev.

---

linux/rpm/build.gradle

The new naming scheme for RPMs is `adoptopenjdk-<version>-<vm>`.
Output from CentOS 7 with JDK 12:
```
[root@6bf4b02f1c66 /]# yum search adoptopenjdk
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
* base: pkg.adfinis-sygroup.ch
* extras: pkg.adfinis-sygroup.ch
* updates: pkg.adfinis-sygroup.ch
============================================== N/S matched: adoptopenjdk ===============================================
adoptopenjdk-12-hotspot.x86_64 : OpenJDK Development Kit 12 (JDK) by AdoptOpenJDK
Name and summary matches only, use "search all" for everything.
[root@6bf4b02f1c66 /]# yum info adoptopenjdk-12-hotspot
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
* base: pkg.adfinis-sygroup.ch
* extras: pkg.adfinis-sygroup.ch
* …
```

Make RPM package name match the Debian’s name

---

wix/Main.hotspot.wxs
wix/Main.openj9.wxs
wix/README.md

To close https://github.com/AdoptOpenJDK/openjdk-installer/issues/103

enable capability to install per user + doc

---

linux/README.md
linux/deb/build.gradle
linux/rpm/build.gradle

* Fedora: Drop 28, add 30
* CentOS, RHEL: Add 8
* Ubuntu: Drop Trusty

Update supported Linux distributions

---

linux/deb/config/jdk-10-hotspot/dependencies.txt
linux/deb/config/jdk-10-openj9/dependencies.txt
linux/deb/config/jdk-11-hotspot/dependencies.txt
linux/deb/config/jdk-11-openj9/dependencies.txt
linux/deb/config/jdk-12-hotspot/dependencies.txt
linux/deb/config/jdk-12-openj9/dependencies.txt
linux/deb/config/jdk-8-hotspot/dependencies.txt
linux/deb/config/jdk-8-openj9/dependencies.txt
linux/deb/config/jdk-9-hotspot/dependencies.txt
linux/deb/config/jdk-9-openj9/dependencies.txt

Its circular dependency with the JDK packages makes the AdoptOpenJDK packages uninstallable on Debian (see #105). Trying to somehow get it to install anyway would result in brittle packages because apt/dpkg provides no guarantees how dependency cycles are going to be resolved.
Without ca-certificates-java, the JDK tools will use the default truststore shipped with the JDK.
This is most likely just an interim fix for #105. I plan to bring back the functionality of `ca-certificates-java` without having to install `ca-certificates-java`.

Remove ca-certificates-java dependency from Debian packages

---

wix/Includes/OpenJDK.Variables.wxi
wix/Main.hotspot.wxs
wix/Main.openj9.wxs

fix hotspot as discuted in https://github.com/AdoptOpenJDK/openjdk-installer/issues/137
fix for openj9 too wich has changed from bin\jvm.dll to bin\server\jvm.dll
closes: https://github.com/AdoptOpenJDK/openjdk-installer/issues/137

fix path for jvm.dll

---

.gitignore
pkgbuild/notarize/notarize.js
pkgbuild/notarize/package.json
pkgbuild/pkgbuild.sh

closes: https://github.com/AdoptOpenJDK/openjdk-installer/issues/145
This PR enables our installers to be notarized to meet Apple's new requirements for 10.14.5 and above.

add notarization to installer

---

linux/create_installer_linux.sh

The build is currently failing with `mktemp: too few X's in template ‘adoptjdkbuild’`.

Add enough Xs to mktemp

---

linux/create_installer_linux.sh

We should validate the contents of the VERSION argument. Typos or mismatches cause changes to the package names and as a result, we might push releases to Artifactory with an invalid name (invalid as in "might break updates"). In the worst case, we'd have to pull a release.
Could someone please take an extra look at the patterns, especially those involving OpenJ9? Do they match the versions used by the build pipelines?

Validate VERSION parameter

---

linux/create_installer_linux.sh

The current implementation does not work. Some patterns are wrong and overall it's the wrong place to solve the problem because the bash script is hard to test. I like to revert it (originally added in #153) until I come up with a better idea.

 Undo VERSION parameter validation

---

linux/buildSrc/src/main/java/net/adoptopenjdk/installer/AbstractBuildLinuxPackage.java
linux/buildSrc/src/main/java/net/adoptopenjdk/installer/BuildDebianPackage.java
linux/buildSrc/src/main/java/net/adoptopenjdk/installer/BuildRpmPackage.java
linux/deb/build.gradle
linux/rpm/build.gradle

I made a mistake in #141 by replacing illegal characters in filenames, too, and not only in the metadata. Only RPMs were affected, producing files like `adoptopenjdk-8-openj9-8u222_b10.openj9_0.15.1-1.x86_64.rpm` instead of `adoptopenjdk-8-openj9-8u222-b10.openj9-0.15.1-1.x86_64.rpm` (`_` instead of `-` after `8u222` and `openj9`).

Remove illegal chars from metadata version only

---

pkgbuild/pkgbuild.sh

while apple has temporarily made notarization easier (https://developer.apple.com/news/?id=09032019a) we can continue as before without hardened runtime enabled.

re enable notarization

---

linux/README.md
linux/rpm/build.gradle

Plus the addition of JDK 13 to the support matrix that was previously undocumented because I forgot to do it.

Add support for Fedora 31, drop Fedora 29

---

pkgbuild/create-installer-mac.sh
pkgbuild/pkgbuild.sh

Build the macOS installer when `CERTIFICATE` is not set. User can add their own customized steps to sign the macOS package.

Add support to disable macOS signing

---

pkgbuild/create-installer-mac.sh

@gdams 
I tested in Microsoft Juniper Pipeline: `https://dev.azure.com/ms-juniper/Juniper/_build/results?buildId=2144&view=logs&j=438df1b3-061f-559b-4ceb-8133ae4cf5b7`. I also add a `echo` command to improve the debug ability. I think the issue you saw `INPUT_DIRECTORY: unbound variable` is probably related to the script cannot find the file.

Fix issue in PR #176

---

linux/README.md
linux/deb/build.gradle
linux/rpm/build.gradle

* Ubuntu: Add upcoming Ubuntu 20.04.
* Fedora: Add upcoming Fedora 32.
* OpenSUSE: Drop OpenSUSE 15.0 (EOL 2019-11), add upcoming OpenSUSE 15.2.

Update supported distributions

---

linux/standalone_create_installer_linux.sh

The download URLs look different for OpenJ9 14+36 than they do for other releases. This workaround handles it for the release of 14+36. Will revert afterwards (or even better, migrate to a more stable solution).

Add temporary workaround for OpenJ9 URL change

---

wix/SourceDir/CreateSourceFolder.AdoptOpenJDK.ps1

- exit with error code and message if regex don't match
- Zip must begin with "^" added
Fix #207

Hardening detection of jdk/jvm/arch in filename

---

wix/SourceDir/CreateSourceFolder.AdoptOpenJDK.ps1

* JDK-NEXT tarballs have no major version number in name
Closes: https://github.com/AdoptOpenJDK/openjdk-build/issues/1712
Signed-off-by: Morgan Davies <morgan.davies@ibm.com>

Account for JDK-Next Binaries

---

wix/Build.OpenJDK_generic.cmd
wix/SourceDir/CreateSourceFolder.AdoptOpenJDK.ps1

Ready to work with artifact OpenJDK_*.zip without major number as we get major java version in job parameter.
All unnumbered (major) zip file is now unzip in a folder "OpenJDK-Latest"
https://github.com/AdoptOpenJDK/openjdk-build/pull/1764 is no longer needed for Windows installer.
Fix : https://github.com/AdoptOpenJDK/openjdk-build/issues/1712
Need also a revert or fix from https://github.com/AdoptOpenJDK/openjdk-build/pull/1754 to return back to normal
This https://github.com/AdoptOpenJDK/openjdk-build/issues/1751 is still relevant
and match the JRE|JDK part of https://github.com/AdoptOpenJDK/openjdk-installer/issues/211

Manage unzip of JDK-Latest without number in file name

---

linux/buildSrc/src/main/java/net/adoptopenjdk/installer/Architecture.java

This will likely fail at present due to the build pipelines being `riscv` instead of `riscv64` but that is being addressed under a separate PR.
Fixes https://github.com/AdoptOpenJDK/openjdk-installer/issues/213
At the moment I don't have a Debian system to test on, and I suspect there is no SuSE port to this platform so that is superfluous.
I have verified that the RedHat rpm produced by this will install and is runnable on my Fedora RISCV system, however it does not uninstall so further work will be required:
```
[root@stage4 /]# rpm -e adoptopenjdk-11-openj9-jre-11.0.0_internal+0_adhoc.jenkins.openj9_openjdk_jdk11-1.riscv64
error: %preun(adoptopenjdk-11-openj9-jre-11.0.0_internal+0_adhoc.jenkins.openj9_openjdk_jdk11-1.riscv64) scriptlet failed, exit status 2
error: …
```

Add RISCV support

---

linux/README.md
linux/build.gradle
linux/deb/build.gradle
linux/rpm/build.gradle

[UPDATED]
Will keep the same gradle task but add optional arguments to specify VENDOR, VENDOR_HOMEPAGE, VENDOR_SROURCE_URL, DEBIAN_ITERATION
**[DEPRECATED INFO BELOW]**
Proposing a new gradle task for building .deb package by any vendor
*VENDOR*:
- vendor value is passed in by providing `-PVENDOR="vendor.."` to the gradle task
- if not specified, it defaults to "AdoptOpenJDK". 
*VENDOR_HOMEPAGE*:
- homepage is passed in by providing `-PVENDOR_HOMEPAGE="www.abc.com"` to the gradle task.
- if not specified, the value defaults to "https://adoptopenjdk.net/"
*Testing Results*:
An example package is created by `./gradlew buildVendorDebPackage` with the following arguments: 
```
-PJDK_DISTRIBUTION_TYPE=JDK 
-PJDK_MAJOR_VERSION=11 
-PJDK_VERSION=11.0.8+2 
-PJDK_VM=hotspot 
-PVENDOR=Microsoft …
```

allow any vendor to produce packages with vendor metadata and name

---

linux/rpm/config/jdk-13-hotspot-jre/postinst.sh
linux/rpm/config/jdk-13-hotspot/postinst.sh
linux/rpm/config/jdk-13-openj9-jre/postinst.sh
linux/rpm/config/jdk-13-openj9/postinst.sh
linux/rpm/config/jdk-14-hotspot-jre/postinst.sh
linux/rpm/config/jdk-14-hotspot/postinst.sh
linux/rpm/config/jdk-14-openj9-jre/postinst.sh
linux/rpm/config/jdk-14-openj9/postinst.sh
linux/rpm/config/jdk-15-hotspot-jre/postinst.sh
linux/rpm/config/jdk-15-hotspot/postinst.sh
linux/rpm/config/jdk-15-openj9-jre/postinst.sh
linux/rpm/config/jdk-15-openj9/postinst.sh

JDK 12+ all had the same priority: 1121. As a result, installing a newer JDK would not replace the old one. The priorities are now as follows:
* 12: 1121
* 13: 1131
* 14: 1141
* 15: 1151

Fix alternatives' priorities on RPM-based systems

---

linux/buildSrc/src/main/java/net/adoptopenjdk/installer/AbstractBuildLinuxPackage.java

Gradle resolves symlinks when copying without retaining the original permissions.

Copy with cp instead of Gradle to preserve links

---

linux/build.gradle

Should have happened as part of #243, but the originating branch was too old which turned the change into a no-op.

Bump RPM iteration

---

pkgbuild/create-installer-mac.sh

ref: 
https://github.com/AdoptOpenJDK/openjdk-build/pull/2064
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1382
When unlocking a keychain, according to the security unlock-keychain syntax, if a keychain isn't specified, it will attempt to unlock the system keychain, which the Jenkins user isn't able to do. This can lead to the infra issue referenced above.

mac: Specify which keychain to unlock when signing mac builds

---

pkgbuild/create-installer-mac.sh

I assume this was an oversight in the original authorship.
If CERTIFICATE is not defined the script will fail because
SIGN_CERT is unbound.
Signed-off-by: Adam Brousseau <adam.brousseau@ca.ibm.com>

Replace SIGN_OPTION with SIGN_CERT

---

wix/Build.OpenJDK_generic.cmd
wix/Includes/OpenJDK.Variables.wxi

This change restores the build number to the fourth potential
REPRO_DIR location (removed accidentally in PR 258), and also 
includes a number of minor changes to aid maintenance:
- Removing unused JEP322_NAME variable
- Removing barely-used JEP322_BASE_NAME variable
- Correcting product version variables so their names more accurately
reflect their contents
Signed-off-by: Adam Farley <adfarley@redhat.com>

Remove unused variables and correct version string variable names

---

pkgbuild/OpenJDKPKG.pkgproj.template
pkgbuild/packagesbuild.sh

During the migration to Packages, we stopped adding the full version number to the PKG metadata. Instead, it was hardcoded to 1.0.
Additionally, this PR fixes inconsistent capitalization of the file OpenJDKPkg.pkgproj.template which is an issue on Macs with a case-sensitive file system.
Fixes #263.

Add full version number to PKG metadata

---

pkgbuild/create-installer-mac.sh
pkgbuild/packagesbuild.sh

When CERTIFICATE is not used, the empty quotes around
SIGN_CERT in the packagebuild command will mess up the
input args. Moving the quotes into the variable will
remove them from the call when the variable doesn't get set.
Fixes #256
Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

Move quotes around SIGN_CERT into variable itself

---

pkgbuild/create-installer-mac.sh

PR https://github.com/AdoptOpenJDK/openjdk-installer/pull/257
moved the SIGN_CERT single quotes into the variable, but that then means they lose their meaning.
Signed-off-by: Andrew Leonard <anleonar@redhat.com>

Ensure SIGN_CERT quoting is preserved

---

linux/README.md
linux/deb/build.gradle
linux/rpm/build.gradle

* Debian: Remove Jessie (EOL), add upcoming Bullseye.
* Ubuntu: Remove Eoan (EOL), add upcoming Hirsute.
* Fedora: Remove 31 (EOL), add upcoming 34, aarch64 and armhfp for >= 33.

Update supported distributions for Linux packages

---

.github/workflows/wix.yml
wix/Build.OpenJDK_generic.cmd
wix/Main.hotspot.wxs
wix/Main.openj9.wxs

1. Check whether `ICEDTEAWEB_DIR` exists before creating the jdk8u MSI installer.
2. Update GitHub action to test this change & Refactor the code format.

Making IcedWeb-Tea optional for JDK 8u Windows MSI Installer

---

linux/standalone_create_installer_linux.sh

The file names on GitHub do not follow the standard conventions.
Will back out the change once the packages have been created.

Add workaround to release 8u282-b08 (arm/aarch64)

---

linux/create_installer_linux.sh

Follow-up to #293, but this one can stay because it's a generally applicable improvement.

Make distribution type matching more robust

---

linux/standalone_create_installer_linux.sh

Removes temporary changes introduced with #293 that were required because the release filenames did not match expectations.

Undo workaround to release 8u282-b08 (arm/aarch64)

---

wix/Includes/OpenJDK.Variables.wxi.template

the current windows aarch64 msi installer displays incorrect architecture information:
this PR will add some checks on the architecture and display the correct architecture information.

fix text string on windows aarch64 msi installer

---

pkgbuild/packagesbuild.sh

These need to be done at the sign stage now

Remove cp commands and plist steps from installer scripts

---

wix/Main.wxs.template

The reg key is now added if not already present.
If present and already "1.8" skip recreating.
If present and <> "1.8" check if major version is newer.
All this tests are depended from the base key wich is different for 1.8 and newer and different for JRE vs JDK
><Property Id="ORACLE_JAVASOFT_BASE_KEY" Value="$(var.OracleJavasoftBaseKey)" />

reg key CurrentVersion not writted with jdk8 #329

---

linuxNew/Jenkinsfile

The current process does not archive the `adoptium-ca-certificates` package which is a dependency of all the temurin `.deb` packages. This PR resolves that.
Fixes https://github.com/adoptium/installer/issues/363 - an attempt to look at an alternative in https://github.com/adoptium/installer/pull/370 has been abandoned.

Ensure adoptium-ca-certificates deb file is archived

---

linuxNew/jdk/redhat/src/packageTest/java/packaging/RpmFiles.java
linuxNew/jdk/suse/src/main/packaging/Dockerfile
linuxNew/jdk/suse/src/main/packaging/temurin/11/temurin-11-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/8/temurin-8-jdk.spec
linuxNew/jdk/suse/src/packageTest/java/packaging/RpmFiles.java

Enable target s390x and ppc64le on x86-86 host on SUSE
Enable SRPM and copy SPRM to destination Directory
close #361 

Enable target s390x and ppc64le on x86-86 host on SUSE

---

.github/workflows/linux.yml
linuxNew/Jenkinsfile
linuxNew/README.md
linuxNew/build.gradle
linuxNew/jdk/redhat/build.gradle
linuxNew/jdk/redhat/src/main/packaging/Dockerfile
linuxNew/jdk/redhat/src/main/packaging/entrypoint.sh
linuxNew/jdk/redhat/src/main/packaging/temurin/8/temurin-8-jdk.spec
linuxNew/jdk/suse/build.gradle
linuxNew/jdk/suse/src/main/packaging/Dockerfile
linuxNew/jdk/suse/src/main/packaging/entrypoint.sh

This PR add's the ability to pass a private GPG key to the docker environment to allow RPM signing to take place
Tested in https://ci.adoptopenjdk.net/job/gdams-packages-linux-pipeline/16/

add GPG key to rpm build

---

linuxNew/Jenkinsfile
linuxNew/jdk/debian/src/main/packaging/temurin/11/debian/rules
linuxNew/jdk/debian/src/main/packaging/temurin/17/debian/rules
linuxNew/jdk/debian/src/main/packaging/temurin/8/debian/rules

This isn't great as it's not currently building the original stuff and the stuff that runs on other machines in parallel, and I've also had to add in a function which doesn't run testing on all platforms because it's complaining about an issue with port 8080 which I haven't got working yet, but while it'll need some subsequent cleanups this fundamentally seems to work and adds the successful production of Temurin `.deb` files on aarch64, ppc64le and s390x (armv7l fails because the machine I've been running on can't run with `-Xmx4g`.
I've removed the `JDK_SOURCE` switch because it wasn't doing much and when I duplicated the buildandtest function it created more duplication leaving it in. Any Jenkinsfile experts out there are more than welcome to improve the syntax as there's much to be …

Add non-x64 Debian architectures to linuxNew jenkins pipeline

---

linuxNew/Jenkinsfile

Lots of people have requested CentOS 7 and RHEL packages to be uploaded

RPM - add missing RHEL and CentOS distros

---

linuxNew/Jenkinsfile

This PR avoids the need for a very long (and hard to parse) list of distributions

DEB: auto generate deb.distribution list from array

---

linuxNew/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec
linuxNew/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
linuxNew/jdk/redhat/src/main/packaging/temurin/8/temurin-8-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/11/temurin-11-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/8/temurin-8-jdk.spec

Examples of what packages default Java RPMs provide:
- https://centos.pkgs.org/8/centos-appstream-aarch64/java-1.8.0-openjdk-1.8.0.312.b07-2.el8_5.aarch64.rpm.html
- https://centos.pkgs.org/8/centos-appstream-aarch64/java-1.8.0-openjdk-devel-1.8.0.312.b07-2.el8_5.aarch64.rpm.html
- https://centos.pkgs.org/8/centos-appstream-aarch64/java-1.8.0-openjdk-headless-1.8.0.312.b07-2.el8_5.aarch64.rpm.html
Fixes #415

Fix provided packages list for Temurin RPM packages

---

linuxNew/jdk/debian/src/main/packaging/temurin/17/debian/changelog
linuxNew/jdk/debian/src/main/packaging/temurin/17/debian/rules
linuxNew/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec

Draft as arm32 and s390x are not yet published (Should be later today)
Also note that unlike #423 I have not included the old version in the Debian changelog for now as it is failing the checks. We'll need to do something consistent between 8 and 11 ...

Update packaging for jdk-17.0.2+8

---

linuxNew/jdk/debian/src/main/packaging/temurin/11/debian/changelog
linuxNew/jdk/debian/src/main/packaging/temurin/11/debian/rules
linuxNew/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec
linuxNew/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/11/temurin-11-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/16/temurin-16-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec

All architectures are now available for JDK11.0.14+9.

Update packaging for jdk-11.0.14+9

---

linuxNew/jdk/debian/src/main/packaging/temurin/11/debian/changelog
linuxNew/jdk/debian/src/main/packaging/temurin/11/debian/rules
linuxNew/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec
linuxNew/jdk/suse/src/main/packaging/temurin/11/temurin-11-jdk.spec

Spec file changes required for the new interim jdk11 release so we can release updated rpm and deb files. Hopefully the extra `.1` won't cause anything to break ;-)

Update linux packaging for JDK 11.0.14.1+1

---

pkgbuild/create-installer-mac.sh

Self-explanatory - traps the default condition which showed up before https://github.com/adoptium/ci-jenkins-pipelines/pull/241 went in. Error was an attempt to use an undefined variable.
```
pkgbuild/create-installer-mac.sh: line 79: JVM: unbound variable
```

mac: Trap case where nether hotspot or openj9 are in the filename

---

pkgbuild/create-installer-mac.sh
wix/Build.OpenJDK_generic.cmd

Fix for the following error in [create_installer_windows](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows):
```
JVM "temurin" not supported : valid values : hotspot, openj9, dragonwell, hotspot openj9, openj9 hotspot
```
This just maps `JVM=temurin` to `JVM=hotspot` to ensure all the values are the same as before. Happy to entertain a discussion on whether this should be changed in the future but for now this should allow the installer to be generated the same as it was before the changes.

create_installer_windows failing with new "temurin" variant support

---

linuxNew/Jenkinsfile

Using single-quotes instead of double-quotes when referencing these sensitive environment variables prevents this type of leaking. 
The current job get information 'The following steps that have been detected may have insecure interpolation of sensitive variables'

Using single-quotes instead of double-quotes when reference credentials

---

pkgbuild/packagesbuild.sh

Internally we realised that it was possible to create a PKG with an invalid architecture specified so this PR sanitises the value before building

pkgbuild: ensure that ARCH is valid

---

linuxNew/jdk/debian/src/main/packaging/temurin/11/debian/rules
linuxNew/jdk/debian/src/main/packaging/temurin/16/debian/rules
linuxNew/jdk/debian/src/main/packaging/temurin/17/debian/rules
linuxNew/jdk/debian/src/main/packaging/temurin/18/debian/rules
linuxNew/jdk/debian/src/main/packaging/temurin/8/debian/rules

Fixes https://github.com/adoptium/installer/issues/443
Tested at https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline/115/:
Previous version (Footprint on disk = 298448Kb:
```
root@odroid-1:/home/sxa# file /usr/lib/jvm/temurin-17-jdk-armhf/lib/libjava.so
/usr/lib/jvm/temurin-17-jdk-armhf/lib/libjava.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
root@odroid-1:/home/sxa# file /usr/lib/jvm/temurin-17-jdk-armhf/bin/java
/usr/lib/jvm/temurin-17-jdk-armhf/bin/java: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, stripped
```
New version (Footprint on disk = 305360Kb)
```
root@odroid-1:/home/sxa# file /usr/lib/jvm/temurin-17-jdk-armhf/lib/libjava.so …
```

Stop stripping binaries in debian packages

---

linuxNew/Jenkinsfile
linuxNew/ca-certificates/debian/build.gradle
linuxNew/ca-certificates/debian/src/packageTest/java/org/adoptium/cacertificates/ChangesVerificationTest.java
linuxNew/ca-certificates/debian/src/packageTest/java/org/adoptium/cacertificates/DebianFlavours.java
linuxNew/jdk/debian/build.gradle
linuxNew/jdk/debian/src/packageTest/java/packaging/DebianFlavours.java

Ubuntu Jammy is the latest LTS release of Ubuntu so needs to be added to the installer matrix

linuxNew: add support for Ubuntu Jammy (22.04)

---

linuxNew/Jenkinsfile
linuxNew/README.md
linuxNew/jdk/redhat/src/packageTest/java/packaging/RedHatFlavoursWithDnf.java

Add the latest version of Fedora to the installer matrix.
Fixes #465

linuxNew add support for Fedora 36

---

linux/ca-certificates/debian/build.gradle
linux/ca-certificates/debian/src/main/packaging/Dockerfile
linux/ca-certificates/debian/src/main/packaging/build.sh
linux/gradlew
linux/jdk/debian/src/main/packaging/Dockerfile
linux/jdk/debian/src/main/packaging/build.sh
linux/jdk/redhat/src/main/packaging/Dockerfile
linux/jdk/redhat/src/main/packaging/build.sh
linux/jdk/suse/src/main/packaging/Dockerfile
linux/jdk/suse/src/main/packaging/build.sh

- for better practice and to reduce maintenance work: create build.sh as static file not generate as step in docker build 
- install tini from dnf not download from github
- remove install "sudo" in dockerfile

refact: move build.sh as file not generate everytime in docker build

---

linux/jdk/debian/src/packageTest/java/packaging/DebianFlavours.java

> https://github.com/adoptium/installer/blob/master/linux/jdk/debian/src/packageTest/java/packaging/DebianFlavours.java#L32-L33
> Debian policy: Oldest, newest and development version.
> Ubuntu policy: Oldest LTS, newest LTS, and development version.
1. [Debian releases](https://wiki.debian.org/DebianReleases#Production_Releases)
1. Add `debian:bookworm`
1. [Ubuntu releases](https://releases.ubuntu.com/)
1. Remove `ubuntu:hirsute`
1. Add `ubuntu:impish` and `ubuntu:kinetic`

Update supported debian distributions

---

linux/Jenkinsfile
linux/README.md
linux/jdk/suse/src/main/packaging/Dockerfile
linux/jdk/suse/src/packageTest/java/packaging/SuseFlavours.java

1. openSUSE Leap 15.1/15.2 have reached their end of life and should be removed. openSUSE Leap 15.4 is available.
* https://en.opensuse.org/Lifetime

Update supported suse distributions

---

linux/Jenkinsfile
linux/ca-certificates/debian/build.gradle
linux/ca-certificates/debian/src/packageTest/java/org/adoptium/cacertificates/ChangesVerificationTest.java
linux/ca-certificates/debian/src/packageTest/java/org/adoptium/cacertificates/DebianFlavours.java
linux/jdk/debian/build.gradle
linux/jdk/debian/src/packageTest/java/packaging/DebianFlavours.java

Impish went EOL on 14th July (https://ubuntu.com/about/release-cycle)

remove impish from linux matrix

---

linux/jdk/redhat/src/main/packaging/build.sh
linux/jdk/suse/src/main/packaging/build.sh

The bug was introduced when move the logic from Dockerfile to build.sh
which double %% is for syntax in Dockerfile so it need to be removed one in the build.sh
Ref: https://github.com/adoptium/adoptium/issues/152#issuecomment-1200800650

fix: gpg sign issue on RPM

---

linux/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec
linux/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/11/temurin-11-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec

RPMs for 11.0.16+8 and 17.0.4+8 were published without being signed.
That issue is fixed by https://github.com/adoptium/installer/pull/509 and causes this problem:
```
Package temurin-17-jdk-17.0.4.0.0.8-1.aarch64.rpm is not signed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
```
This bumps the spec version so that we can republish in a way that means the the new fixed versions will be picked up by default.

Bump RPM spec files to version 2 in order to allow rebuild for signing

---

linux/jdk/debian/src/main/packaging/temurin/8/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/8/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/8/temurin-8-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/8/temurin-8-jdk.spec

Updates for the new version. Cannot be used successfully until arm32 tarballs have been pushed.

Update jdk8 installers to jdk8u345-b01

---

linux/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec
linux/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/11/temurin-11-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec

Resets the spec bump introduced in https://github.com/adoptium/installer/pull/510 in order to avoid anyone accidentally using `2` for the next quarterly release. Note that this needs general doc updates relating to installer rebuilds for all distros (Ref: #debian

Reset spec_release to 1 to avoid accidentally using 2 on next update

---

linux/jdk/redhat/build.gradle
linux/jdk/redhat/src/packageTest/java/packaging/DnfOperationsTest.java
linux/jdk/redhat/src/packageTest/java/packaging/YumOperationsTest.java
linux/jdk/suse/build.gradle
linux/jdk/suse/src/packageTest/java/packaging/ZypperOperationsTest.java

- GHA test case without gpg
- https://ci.adoptopenjdk.net/job/Sophia-adoptium-packages-linux-pipeline/144/artifact/jdk/redhat/build/reports/tests/checkJdkRedHat/classes/packaging.DnfOperationsTest.html test case with -PGPG_KEY set : to have a negative debug to print assert `Signature   : RSA/SHA256, Wed Aug  3 15:13:10 2022, Key ID 843c48a565f8f04b` should be matched
- https://ci.adoptopenjdk.net/job/Sophia-adoptium-packages-linux-pipeline/143/ test cas with -PGPG_KEY set: to have a positive case
- uplift dependency version : most were released 1.5yrs ago to latest ones
Ref: https://github.com/adoptium/installer/issues/513

test: update tests for checking if rpm is signed when we use -PGPG_KEY

---

.github/workflows/linux.yml
README.md
linux/Jenkinsfile
linux/README.md

1. Docker 20.10+ is required to build.
1. Because the `--mount` option is used without specify experimental dockerfile `#syntax` directive. https://github.com/adoptium/installer/blob/master/linux/jdk/redhat/src/main/packaging/Dockerfile#L27
> https://docs.docker.com/engine/release-notes/#20100
> buildkit,dockerfile: Support for RUN --mount options without needing to specify experimental dockerfile #syntax directive. moby/buildkit#1717
2. Remove `COMPOSE_DOCKER_CLI_BUILD`
1. Because docker compose is not used.
2. Because `COMPOSE_DOCKER_CLI_BUILD=1` is the default setting. https://docs.docker.com/compose/reference/envvars/#compose_docker_cli_build

Documentation: Docker 20.10+ is required to build

---

.github/workflows/linux.yml
linux/Jenkinsfile
linux/README.md
linux/build.gradle
linux/jdk/debian/build.gradle
linux/jdk/debian/src/main/packaging/build.sh
linux/jdk/redhat/build.gradle
linux/jdk/redhat/src/main/packaging/build.sh
linux/jdk/redhat/src/packageTest/java/packaging/DnfOperationsTest.java
linux/jdk/redhat/src/packageTest/java/packaging/RedHatFlavoursWithDnf.java
linux/jdk/redhat/src/packageTest/java/packaging/RedHatFlavoursWithYum.java
linux/jdk/redhat/src/packageTest/java/packaging/RpmFiles.java
linux/jdk/redhat/src/packageTest/java/packaging/YumOperationsTest.java
linux/jdk/suse/build.gradle
linux/jdk/suse/src/main/packaging/build.sh
linux/jdk/suse/src/packageTest/java/packaging/RpmFiles.java
linux/jdk/suse/src/packageTest/java/packaging/ZypperOperationsTest.java
linux/settings.gradle

- add  support ARCH with selection but not include "all" 
- remove support VERSION with value "all"
- make DISTRO to only "all" "Debian" "RedHat" and "Suse"
- pass in jdkversion as variable for rpm
-  default use node pool "dockerBuild&&linux&&x64", debian non x64 use pool "docker&&linux&&${ARCH}"
- change from matrix to three different stages per each distro
- enable DOCKER_BUILDKIT on all even for Debian+s390x
- only do git clone "installer.git" once and stash folder "linux" into different distro build stage
- remove rpm for Centos8 publish to jfrog (already have rocky8)
- add support in jenkins for 
-  enableDebug for more build info
-  split UPLOAD into "uploadPackage" and "uploadSRCRPM"
-  can use the same job for test repo or branch (for debug purpose)
-  add simple description of …

feat: add capability to run installer per jdk version or distro selection 

---

linux/Jenkinsfile
linux/jdk/debian/src/main/packaging/build.sh

Fix: https://github.com/adoptium/installer/issues/531
- fix ARCH=all when DISTRO=Debian:
`dpkg-buildpackage ` wont take parameters to determinate arch, it only uses the host machine(jenkins agent)'s arch to build package. that's why the handle for debian package is different from rpm package. 
- fix linter
Test on debian + all + jdk19 (no upload) : https://ci.adoptopenjdk.net/view/work-in-progress/job/Sophia-adoptium-packages-linux-pipeline/173/console
aborted due to only one ppc64le machine availabe for deb, but from log x86_64 and arm64 are done
```
changestool /home/builder/workspace/temurin-19-jdk_19+36_amd64.changes setdistribution buster bullseye bionic focal jammy
changestool /home/builder/workspace/temurin-19-jdk_19+36_arm64.changes setdistribution buster bullseye bionic focal …
```

fix: debian linux installer should be run on different node when set ARCH="all"

---

linux/jdk/redhat/src/packageTest/java/packaging/DnfOperationsTest.java
linux/jdk/redhat/src/packageTest/java/packaging/YumOperationsTest.java

the yum/dnf update commands take a long time and slow down the CI unnecessarily.

linux: remove unnecessary update commands

---

linux/Jenkinsfile
linux/jdk/suse/src/packageTest/java/packaging/ZypperOperationsTest.java

from https://github.com/adoptium/installer/commit/c2d0c59f57a7dc4b269eaca70f4adf0979630512
name was change from uploadRPMArtifacts to uploadRpmArtifacts
it should be ended in arm7hl not arm7l
which showed the same for Sep jdk19 release
remove zypper update test which fails very often and slow down release
https://github.com/adoptium/installer/issues/549

fix: wrong function name and target name

---

linux/Jenkinsfile

1. Add check(findFiles()) and sleep before upload for RPM(redhat suse) and Deb
to prevent - error: "No files were affected in the upload process" which  could be when build just done jenkins not find archived file
2. fix the missing logic, when only choose one arch for RPM it should only try to upload this arch not "all"
Below test1 and2  run failed because of packages already exist in jfrog so the overridden is not permitted but we do not see "No files were affected in the upload process" error any more
- Test1: only build suse jdk19 with ppc64
```
Upload artifacts for 19 - ppc64le - Suse
[Pipeline] echo
Prepare for ppc64le.rpm
[Pipeline] findFiles
[Pipeline] rtUpload
Executing command: /bin/sh -c git log --pretty=format:%s -1
[consumer_0] Deploying artifact: …
```

fix: add sleep and this fixed problem of error when upload

---

.github/workflows/linux.yml
.github/workflows/pgkbuild.yml
.github/workflows/wix.yml

Fix the GitHub action dependencies to specific version hashes, and ensure they have minimal permissions.
Part of https://github.com/adoptium/adoptium/issues/187

Fix dependency action hashes and restrict permissions

---

linux/Jenkinsfile

Seems we have updated README for fedora37 before it was officially released  but not enable it from the build.
Fixes: https://github.com/adoptium/installer/issues/566

feat: add support for fedora 37

---

linux/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec
linux/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
linux/jdk/redhat/src/main/packaging/temurin/18/temurin-18-jdk.spec
linux/jdk/redhat/src/main/packaging/temurin/19/temurin-19-jdk.spec
linux/jdk/redhat/src/main/packaging/temurin/8/temurin-8-jdk.spec

I noticed this while attempting to determine why osbuild-composer bombs out because temurin-17-jdk dependencies seem to not be satisfied when osbuild's org.osbuild.rpm phase attempts to install packages in an empty build root.
The temurin jdk spec files have an empty %%pretrans section, meaning there isn't anything to be run in it, but that doesn't mean rpm would not try to process that section when starting the install transaction ;( This is because in an empty build root there is absolutely nothing yet installed.
In any case, it is severely discouraged to use %%pretrans at all and most up-to-date rpm documentation seem to prohibit its use with a shell interpreter.
Please see https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#pretrans and …

get rid of %%pretrans since nothing uses it

---

test/functional/wintps/build.xml
test/functional/wintps/playlist.xml
test/functional/wintps/runInstallerTests.sh

First step of #559 
Co-authored-by: Sophia Guo <sophia.gwf@gmail.com>
Co-authored-by: Shelley Lambert <slambert@gmail.com>

initial step to add windows installer tests

---

.github/workflows/linux.yml
linux/jdk/alpine/src/main/packaging/temurin/11/APKBUILD
linux/jdk/alpine/src/main/packaging/temurin/17/APKBUILD
linux/jdk/alpine/src/main/packaging/temurin/19/APKBUILD
linux/jdk/alpine/src/main/packaging/temurin/20/APKBUILD
linux/jre/alpine/src/main/packaging/temurin/11/APKBUILD
linux/jre/alpine/src/main/packaging/temurin/17/APKBUILD
linux/jre/alpine/src/main/packaging/temurin/19/APKBUILD
linux/jre/alpine/src/main/packaging/temurin/20/APKBUILD

Add all files from source packages to target APK  
and remove "virtual package" from dependencies as it is empty now.
Resolves #613 & #631 
Should be tested in the context of mercedes-benz/sechub#1794 // @Jeeppler + @ryanlewis

Add all files from source packages to target APK

---

linux/jdk/redhat/src/packageTest/java/packaging/RedHatFlavoursWithYum.java
linux/jre/redhat/src/packageTest/java/packaging/RedHatFlavoursWithYum.java

Fixed issue where checking RPM builds on aarch64 attempts to pull non-supported image (redhat/UBI7)

---

linux/jdk/debian/src/main/packaging/entrypoint.sh
linux/jdk/redhat/src/main/packaging/entrypoint.sh
linux/jdk/suse/src/main/packaging/entrypoint.sh
linux/jre/debian/src/main/packaging/entrypoint.sh
linux/jre/redhat/src/main/packaging/entrypoint.sh
linux/jre/suse/src/main/packaging/entrypoint.sh

Fixed infrequent 'permission denied' bug when reading/writing to output folder for rpm or deb builds

Fixed infrequent 'permission denied' bug

---

linux/jre/debian/src/main/packaging/temurin/8/debian/rules

Update Debian checksums for JRE8 / PPC64 LE & ARM32

Update Debian checksums for JRE8 / PPC64 LE & ARM32

---

linux/ca-certificates/debian/src/main/packaging/debian/changelog
linux/ca-certificates/debian/src/packageTest/java/org/adoptium/cacertificates/AptOperationsTest.java

Fixes https://github.com/adoptium/adoptium-support/issues/816 and is the final step in resolving https://github.com/adoptium/installer/issues/670 (Note: Most of the support was added in https://github.com/adoptium/installer/pull/591 but the ca-certificates package does not get pushed to new directories unless a version change it made, which is what this PR will do.

Add Debian Bookworm support to ca-certificates package

---

linux/jdk/debian/src/main/packaging/microsoft/11/debian/control
linux/jdk/debian/src/main/packaging/microsoft/17/debian/control

Changes the dependency from `adoptium-ca-certificates` to `ca-certificates`.

Change Microsoft dependency to ca-certificates

---

linux/jdk/alpine/src/main/packaging/temurin/17/APKBUILD
linux/jdk/debian/src/main/packaging/temurin/17/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/17/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec
linux/jre/alpine/src/main/packaging/temurin/17/APKBUILD
linux/jre/debian/src/main/packaging/temurin/17/debian/changelog
linux/jre/debian/src/main/packaging/temurin/17/debian/rules
linux/jre/redhat/src/main/packaging/temurin/17/temurin-17-jre.spec
linux/jre/suse/src/main/packaging/temurin/17/temurin-17-jre.spec

Styled after the [April PR](https://github.com/adoptium/installer/pull/660/files)

Installer updates for JDK17 for July 2023 release

---

linux/jdk/alpine/src/main/packaging/temurin/11/APKBUILD
linux/jdk/debian/src/main/packaging/temurin/11/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/11/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/11/temurin-11-jdk.spec
linux/jre/alpine/src/main/packaging/temurin/11/APKBUILD
linux/jre/debian/src/main/packaging/temurin/11/debian/changelog
linux/jre/debian/src/main/packaging/temurin/11/debian/rules
linux/jre/redhat/src/main/packaging/temurin/11/temurin-11-jre.spec
linux/jre/suse/src/main/packaging/temurin/11/temurin-11-jre.spec

Based on the [April 2023 JDK11 updates](https://github.com/adoptium/installer/pull/661).
@steelhead31 - Could you take a look at this before formal reviews are solicited, please?

Installer updates for JDK11 for July 2023 release

---

linux/jdk/alpine/src/main/packaging/temurin/8/APKBUILD
linux/jdk/debian/src/main/packaging/temurin/8/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/8/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/8/temurin-8-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/8/temurin-8-jdk.spec
linux/jre/alpine/src/main/packaging/temurin/8/APKBUILD
linux/jre/debian/src/main/packaging/temurin/8/debian/changelog
linux/jre/debian/src/main/packaging/temurin/8/debian/rules
linux/jre/redhat/src/main/packaging/temurin/8/temurin-8-jre.spec
linux/jre/suse/src/main/packaging/temurin/8/temurin-8-jre.spec

Styled after the changes in [April](https://github.com/adoptium/installer/pull/518/files).

Installer updates for JDK8 for July 2023 release

---

linux/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec
linux/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
linux/jdk/redhat/src/main/packaging/temurin/8/temurin-8-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/11/temurin-11-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/8/temurin-8-jdk.spec

Fixes #705 
Installer tests fail as Thursday August 08th is not a valid date.. appears it should be * Thu Aug 18 2022 , there is a similar issue in the Suse spec file for an April date. The recent bump to container versions for checking RPMs, now appears to validate dates.
* Thu Aug 08 2022 Eclipse Adoptium Package Maintainers <temurin-dev@eclipse.org> 8.0.345.0.0.1.adopt0

Fix errant Date in RPM spec for JDK8

---

linux/Jenkinsfile

Fix the mapping Of arm32 parameter in jenkins (armv7l) to value required in artifactory (armv7hf)

Fix Mapping Of arm32 parameter in jenkins to value required

---

linux/Jenkinsfile

Always translate armv7l into armv7hl for RHEL & Suse release packages, to ensure consistency with artifactory.

Fix Handling of Arm32 for RHEL & Suse

---

.github/workflows/cacert-publish.yml
linux/Jenkinsfile

Switching to the CLI should be more stable for uploads. I've already installed and configured the plugin in jenkins.

migrate to using jfrog CLI for uploads

---

linux/jdk/alpine/src/main/packaging/temurin/11/APKBUILD
linux/jdk/alpine/src/main/packaging/temurin/17/APKBUILD
linux/jdk/debian/src/main/packaging/temurin/11/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/11/debian/rules
linux/jdk/debian/src/main/packaging/temurin/17/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/17/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec
linux/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/11/temurin-11-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec
linux/jre/alpine/src/main/packaging/temurin/11/APKBUILD
linux/jre/alpine/src/main/packaging/temurin/17/APKBUILD
linux/jre/debian/src/main/packaging/temurin/11/debian/changelog
linux/jre/debian/src/main/packaging/temurin/11/debian/rules
linux/jre/debian/src/main/packaging/temurin/17/debian/changelog
linux/jre/debian/src/main/packaging/temurin/17/debian/rules
linux/jre/redhat/src/main/packaging/temurin/11/temurin-11-jre.spec
linux/jre/redhat/src/main/packaging/temurin/17/temurin-17-jre.spec
linux/jre/suse/src/main/packaging/temurin/11/temurin-11-jre.spec
linux/jre/suse/src/main/packaging/temurin/17/temurin-17-jre.spec

Update APK, deb and rpm spec files for release.

Installer updates for JDK11 & JDK17 for August 2023 respin releases

---

.github/workflows/cacert-publish.yml
linux/Jenkinsfile
linux/README.md
linux/ca-certificates/debian/build.gradle
linux/ca-certificates/debian/src/packageTest/java/org/adoptium/cacertificates/ChangesVerificationTest.java
linux/ca-certificates/debian/src/packageTest/java/org/adoptium/cacertificates/DebianFlavours.java
linux/jdk/debian/src/main/packaging/build.sh
linux/jdk/debian/src/packageTest/java/packaging/DebianFlavours.java
linux/jre/debian/src/main/packaging/build.sh
linux/jre/debian/src/packageTest/java/packaging/DebianFlavours.java

This fixes the failures in the PR automated checks due to ubuntu 22.10's end of life

removed ubuntu 22.10 support due to EoL

---

linux/jdk/redhat/src/main/packaging/temurin/21/temurin-21-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/21/temurin-21-jdk.spec
linux/jre/redhat/src/main/packaging/temurin/21/temurin-21-jre.spec
linux/jre/suse/src/main/packaging/temurin/21/temurin-21-jre.spec

Remove PPC64LE for JDK21+35 RHEL & SUSE to allow release of x64 and arm64
Also correct issue with lowercase U in spec files.

Installers: Remove PPC64LE for JDK21+35 RHEL & SUSE

---

linux/Jenkinsfile

Fixes #752 
The upload of Alpine artifacts fails where one artifact already exists, this is caused by the globbing of filenames into a list. To resolve this, passing the filename directly to the generic upload function resolves this.

Installers: Fix Alpine Upload To Use Specific Filenames.

---

linux/jdk/debian/src/main/packaging/temurin/17/debian/changelog
linux/jre/debian/src/main/packaging/temurin/17/debian/changelog

Fix JDK17.0.9 Debian Version Numbers In The Changelog
Updated from 17.0.9.0+9 to 17.0.9.0.0+9

Fix JDK17.0.9 Debian Version Numbers In The Changelog

---

linux/Jenkinsfile

Update jenkinsfile so that version number is correctly passed through to the Alpine and Debian gradle builds, when ARCH parameter is set to ALL, this has been tested in a non-destructive fashion, in my test harness.. https://ci.adoptium.net/job/scott-fryer-adoptium-packages-linux-pipeline_new/237/ , https://ci.adoptium.net/job/scott-fryer-adoptium-packages-linux-pipeline_new/236 , https://ci.adoptium.net/job/scott-fryer-adoptium-packages-linux-pipeline_new/234 & https://ci.adoptium.net/job/scott-fryer-adoptium-packages-linux-pipeline_new/230
Fixes #764

Ensure version number is passed for Alpine & Debian installer builds

---

codesign/eclipse-notarize.sh

Fixes https://github.com/adoptium/installer/issues/737
Remove set -eu, and check rc and echo responses for more debug in case of failure...
Test run with this PR: https://ci.adoptium.net/job/build-scripts/job/release/job/sign_installer_test/3/console

Check notarize-service curl RC and output failure response

---

wix/Main.wxs.template

Replaced msi properties which are evaluated at runtime with variables that are evaluated at build time. 

---

linux/Jenkinsfile
linux/README.md
linux/jdk/suse/src/main/packaging/Dockerfile
linux/jdk/suse/src/packageTest/java/packaging/SuseFlavours.java
linux/jre/suse/src/main/packaging/Dockerfile
linux/jre/suse/src/packageTest/java/packaging/SuseFlavours.java

This is in draft while it's undergoing testing, but this adds support for OpenSuSE 15.5 - the current verison - into our packaging process to ensure that users using that distribution can follow the installation instructions without modification on the latest patch level. Note that this also adjusts the process to build the package on OpenSuSE 15.5 instead of 15.4 as the base image.
Potential alternative options:
- Add 15.6 which is available alpha for OpenSuSE 
- Remove 15.3 (out of support Dec 2022) to keep the number of distributions at 2, and potentially also rmove 15.4 since that is also out of support as of December 2023
Draft until I ensure it can be built successfully.
Fixes https://github.com/adoptium/installer/issues/792

Add OpenSuSE 15.5 as a supported distribution

---

linux/jdk/debian/src/main/packaging/temurin/21/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/21/temurin-21-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/21/temurin-21-jdk.spec

Fixes https://github.com/adoptium/temurin-build/issues/3624#issuecomment-1915272320 (hopefully!)
Note that I haven't adjusted `redhat/src/main/packaging/microsoft/21/msopenjdk-21.spec` which still has the `rm`
I have not tested this, so if a review can fdire off a test and see if the package contains `libfreetype.so` after this then that would be appreciated.

Reinstate libfreetype install on JDK21

---

linux/jdk/debian/src/main/packaging/temurin/21/debian/changelog
linux/jdk/redhat/src/main/packaging/temurin/21/temurin-21-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/21/temurin-21-jdk.spec
linux/jre/debian/src/main/packaging/temurin/21/debian/changelog
linux/jre/redhat/src/main/packaging/temurin/21/temurin-21-jre.spec
linux/jre/suse/src/main/packaging/temurin/21/temurin-21-jre.spec

Fixes #823 
Bump the RPM spec, and the debian version numbers to allow an update to include the freetype library fix, made as part of https://github.com/adoptium/installer/pull/812

Bump RPM spec & Debian versions to JDK21.0.2.0.0+13-2

---

linux/jdk/debian/src/main/packaging/temurin/21/debian/control
linux/jdk/debian/src/main/packaging/temurin/21/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/21/temurin-21-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/21/temurin-21-jdk.spec
linux/jre/debian/src/main/packaging/temurin/21/debian/control
linux/jre/debian/src/main/packaging/temurin/21/debian/rules
linux/jre/redhat/src/main/packaging/temurin/21/temurin-21-jre.spec
linux/jre/suse/src/main/packaging/temurin/21/temurin-21-jre.spec

Fixes #826 
Since JDK21 is now supported on s390x, the linux packages process needs updating to support this.
These changes have been tested as dry runs in my test pipeline (https://ci.adoptium.net/job/doptium-packages-linux-pipeline_new-scottfryer/)
These will be published for s390x for the first time , as part of the spec -2 version, which has the freetype fix, see #823  & #824

Add Installers Support For JDK/JRE 21 s390x Linux ( Debian, RHEL , Suse )

---

linux/jre/redhat/src/main/packaging/temurin/21/temurin-21-jre.spec
linux/jre/suse/src/main/packaging/temurin/21/temurin-21-jre.spec

Fixes #830 
Following the bug and fix identified and carried out, the spec version for jre21 RHEL & SUSE on ppc64le requires a bump to allow those packages to be republished.

Bump RPM for JRE21/ppc64le RHEL & SUSE versions to JDK21.0.2.0.0+13-3 

---

linux/jdk/alpine/src/main/packaging/temurin/22/APKBUILD
linux/jdk/debian/src/main/packaging/temurin/22/debian/control
linux/jdk/debian/src/main/packaging/temurin/22/debian/rules
linux/jdk/redhat/src/main/packaging/temurin/22/temurin-22-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/22/temurin-22-jdk.spec
linux/jre/alpine/src/main/packaging/temurin/22/APKBUILD
linux/jre/debian/src/main/packaging/temurin/22/debian/control
linux/jre/debian/src/main/packaging/temurin/22/debian/rules
linux/jre/redhat/src/main/packaging/temurin/22/temurin-22-jre.spec
linux/jre/suse/src/main/packaging/temurin/22/temurin-22-jre.spec

These files have s390x removed due to some blocking tests, this PR will allow publishing of all other linux installers. A 2nd PR to publish the s390x installers ( and an additional one to come will also be made, to include riscv support )

Update JDK22 Installer files for JDK22+36 Release

---

wix/Build.OpenJDK_generic.cmd
wix/README.md

Allows vendors to set custom filenames for MSIs and related files by setting the `OUTPUT_BASE_FILENAME` environment variable

Added ability to change output msi filename

---

wix/Includes/OpenJDK.Variables.wxi.template
wix/Main.wxs.template

The enumerator for the ARM64 TARGETDIR was set to ProgramFilesARMFolder, which doesn't seem to exist in Wix (3/4/5) any longer ([see here for details](https://wixtoolset.org/docs/v3/bundle/bundle_built_in_variables/))
Also, see [this document](https://learn.microsoft.com/en-us/windows/arm/faq#what-program-files-folder-should-i-use-to-install-my-arm64-application-) for a discussion on where applications for different architectures should be installed on Windows.
So, for the OpenJDK Windows installers, the following folders will be used:
- x86-32: `C:\Program Files (x86)\<vendor>\jdk-x`
- x64: `C:\Program Files\<vendor>\jdk-x`
- ARM64: `C:\Program Files\<vendor>\jdk-x`
Fixes #858

Correction to Windows ARM64 installer location

---

.github/workflows/cacert-publish.yml
linux/ca-certificates/debian/build.gradle
linux/ca-certificates/debian/src/main/packaging/debian/changelog
linux/ca-certificates/debian/src/packageTest/java/org/adoptium/cacertificates/AptOperationsTest.java
linux/ca-certificates/debian/src/packageTest/java/org/adoptium/cacertificates/ChangesVerificationTest.java
linux/ca-certificates/debian/src/packageTest/java/org/adoptium/cacertificates/DebianFlavours.java
linux/jdk/debian/src/main/packaging/build.sh
linux/jdk/debian/src/packageTest/java/packaging/DebianFlavours.java

Add updates for new distros...

Update cacerts for debian 13 & ubuntu 24

---

.github/workflows/cacert-publish.yml

this currently is working (presumably due to a change in the way the jf CLI handles error handling

Improve cacert upload check logic

---

.github/workflows/linux.yml
.github/workflows/linuxTriage.yml

We've been missing certain issues with dependency upgrades that aren't being tested correctly with the automatic matrix generator. This PR switches it to just run all build/tests which we can comfortably do now we have more GH actions minutes.
Also applies a fix to resolve the breaking changes in v4 upload/download artifacts

linux: run tests on all files

---

linux/Jenkinsfile

Reverts a change that looks to have been accidentally introduced as part of https://github.com/adoptium/installer/pull/847
Fixes https://github.com/adoptium/installer/issues/892 (once rebuilt appropriately)

Fix alpine/aarch64 apk files (which are currently x64)

---

linux/Jenkinsfile
linux/jdk/debian/src/main/packaging/temurin/17/debian/control
linux/jdk/debian/src/main/packaging/temurin/17/debian/rules
linux/jdk/redhat/src/main/packaging/Dockerfile
linux/jdk/redhat/src/main/packaging/build.sh
linux/jdk/redhat/src/main/packaging/temurin/17/temurin-17-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/17/temurin-17-jdk.spec
linux/jre/debian/src/main/packaging/temurin/17/debian/control
linux/jre/debian/src/main/packaging/temurin/17/debian/rules
linux/jre/redhat/src/main/packaging/Dockerfile
linux/jre/redhat/src/main/packaging/temurin/17/temurin-17-jre.spec
linux/jre/suse/src/main/packaging/temurin/17/temurin-17-jre.spec

Also Fixes #905 
Update the specfiles and jenkinsfile for the release of JDK17 for riscv64.
Also reverts the docker image update for the rpm package build to Fedora 38 to avoid the issue with gpg signing.

Update Spec Files For JDK17 RiscV Release

---

linux/jre/debian/src/main/packaging/build.sh
linux/jre/debian/src/packageTest/java/packaging/DebianFlavours.java

Missing from PR: https://github.com/adoptium/installer/pull/868
Add the 2 new distributions for the jres.

Add missing distributions for the JRE packages

---

wix/Lang/OpenJDK.Base.zh-cn.wxl.template
wix/Lang/OpenJDK.Base.zh-tw.wxl.template

translation is based on changes from https://github.com/adoptium/installer/pull/945/files
```
<String Id="FeatureEnvironmentTitle" Value="Modify PATH variable" />
<String Id="FeatureEnvironmentDescription" Value="Modify PATH environment variable by prepending the JDK installation directory to the beginning of PATH." />
<String Id="FeatureJavaHomeTitle" Value="Set or override JAVA_HOME variable" />
<String Id="FeatureJavaHomeDescription" Value="Sets or overrides JAVA_HOME environment variable with the JDK installation directory." />
<String Id="BrowseDlg_Title" Value="[ProductName] Browse" />
```

docs: update title and description for locale zh

---

linux/jdk/alpine/src/main/packaging/temurin/11/APKBUILD
linux/jdk/alpine/src/main/packaging/temurin/8/APKBUILD
linux/jdk/debian/src/main/packaging/temurin/11/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/11/debian/rules
linux/jdk/debian/src/main/packaging/temurin/8/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/8/debian/rules
linux/jdk/redhat/src/main/packaging/build.sh
linux/jdk/redhat/src/main/packaging/temurin/11/temurin-11-jdk.spec
linux/jdk/redhat/src/main/packaging/temurin/8/temurin-8-jdk.spec
linux/jdk/suse/src/main/packaging/build.sh
linux/jdk/suse/src/main/packaging/temurin/11/temurin-11-jdk.spec
linux/jdk/suse/src/main/packaging/temurin/8/temurin-8-jdk.spec
linux/jre/alpine/src/main/packaging/temurin/11/APKBUILD
linux/jre/alpine/src/main/packaging/temurin/8/APKBUILD
linux/jre/debian/src/main/packaging/temurin/11/debian/changelog
linux/jre/debian/src/main/packaging/temurin/11/debian/rules
linux/jre/debian/src/main/packaging/temurin/17/debian/rules
linux/jre/debian/src/main/packaging/temurin/8/debian/changelog
linux/jre/debian/src/main/packaging/temurin/8/debian/rules
linux/jre/redhat/src/main/packaging/build.sh
linux/jre/redhat/src/main/packaging/temurin/11/temurin-11-jre.spec
linux/jre/redhat/src/main/packaging/temurin/8/temurin-8-jre.spec
linux/jre/suse/src/main/packaging/build.sh
linux/jre/suse/src/main/packaging/temurin/11/temurin-11-jre.spec
linux/jre/suse/src/main/packaging/temurin/8/temurin-8-jre.spec

Updates required for JDK8 & JDK11 Alpine, Debian, RH & SUSE packages.
Also includes a fix, which was preventing GPG signing from working.
Testing ok.

JULY CPU - JDK8 & JDK11 Updates For Shipping Linux Packages

---

linux/Jenkinsfile
linux/jdk/debian/src/main/packaging/temurin/11/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/17/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/21/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/23/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/8/debian/changelog
linux/jre/debian/src/main/packaging/temurin/11/debian/changelog
linux/jre/debian/src/main/packaging/temurin/17/debian/changelog
linux/jre/debian/src/main/packaging/temurin/21/debian/changelog
linux/jre/debian/src/main/packaging/temurin/23/debian/changelog
linux/jre/debian/src/main/packaging/temurin/8/debian/changelog

- changelog changes were missing, and it is these that determine the build target filenames (!)
Test publish using this branch: https://ci.adoptium.net/job/adoptium-packages-linux-pipeline_new/1648/

Add missing changelog changes

---

linux/Jenkinsfile

Fixes #1053 
Add fedora 41 & 42 distributions, so that installer rpms can be pushed to artifactory.

Add Fedora 41 & 42 distributions.

---

linux/jdk/debian/src/main/packaging/temurin/11/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/17/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/21/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/23/debian/changelog
linux/jdk/debian/src/main/packaging/temurin/8/debian/changelog
linux/jre/debian/src/main/packaging/temurin/11/debian/changelog
linux/jre/debian/src/main/packaging/temurin/17/debian/changelog
linux/jre/debian/src/main/packaging/temurin/21/debian/changelog
linux/jre/debian/src/main/packaging/temurin/23/debian/changelog
linux/jre/debian/src/main/packaging/temurin/8/debian/changelog

Following the merge of https://github.com/adoptium/installer/pull/1075 
A new version of the debian packages is required to be published to make them available for Ubuntu 24.10

Bump package version for Debian republish

---

wix/Build.OpenJDK_generic.cmd

The 10.0.17763.0 is not installed on machines where we install VS2022 from Build Tools. It is assumed that it was installed via some of the earlier VS version roles in our playbooks. This PR updates the version used by the WiX installer so that it will currently run on machines which have only had the VS2022 compiler (the one used by all of the Temurin builds now).
Without this fix it fails when trying to do some locale related activities. Found as part of https://github.com/adoptium/infrastructure/issues/3286#issuecomment-2504207097
```
Building setup translation for culture "de-de" with LangID "1031"...
Input Error: Can not find script file "C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\WiLangId.vbs".
WiLangId failed with : 1
Failed to generate setup translation of culture …
```

Update SDK version used by WiX installer to one that we install with VS2022

---

linux_new/Jenkinsfile

The handling of none linux packages, has shown a typo in printlin rather than println.
Also as the upstream job that triggers the build of the new linux packages cannot be selective, I need to handle the additional parameters to reduce entries in the jenkins warning logs. These parameters will not be used, just added to the pipeline to remove the warning about unhandled parameters.
Part of https://github.com/adoptium/installer/issues/1005

Improve jenkins error logging in installer jenkinsfile & fix typo #1103

---

linux_new/Jenkinsfile

A bug was spotted during the release cycle, whereby it was incorrectly trying to determine which alpine node to build on for a non alpine package build.
This bug fix amends the node identification to be based on the type of packages ( alpine / or non alpine ) being built.
Part of #1005

BugFix : Update automated installer production to validate architecture per distro

---

linux_new/Jenkinsfile

Fixes #1110 
The passing of the relevant key to the gradle builds to produced sign rpms & apks was not working correctly due to the calling of the gradle build outside of the withCredentials block.
Alpine needs the rsa gpg key  
Rhel / Suse need the gpg key  
Debian does not use the jenkins provided gpg key.
This code explicitly forces each package type to be built and signed correctly.
Once this is merged, I'll push updated packages for everything that has already been released.

Bugfix: Automatically generated linux installer packages are not being signed.

---

linux_new/Jenkinsfile
linux_new/jdk/suse/src/main/packaging/temurin/8/temurin-8-jdk.template.j2
linux_new/jre/suse/src/main/packaging/temurin/8/temurin-8-jre.template.j2

The new jdk8 templates for SUSE were not correctly copied, and have required a few updates.
In addition a couple of labels in the jenkinsfile were incorrectly formatted.
Fixes #1118

Update SUSE JDK8 Templates

---

linux/jdk/alpine/src/main/packaging/entrypoint.sh
linux/jre/alpine/src/main/packaging/entrypoint.sh
linux_new/Jenkinsfile
linux_new/jdk/alpine/src/main/packaging/entrypoint.sh
linux_new/jdk/suse/src/main/packaging/temurin/8/temurin-8-jdk.template.j2
linux_new/jre/alpine/src/main/packaging/entrypoint.sh
linux_new/jre/suse/src/main/packaging/temurin/8/temurin-8-jre.template.j2

PLEASE DO NOT MERGE THIS - I NEED TO MAKE A SMALL CHANGE TO THE JENKINS CONFIGURATION FOR THE NEW PACKAGE BUILD PROCESS - I'LL MERGE ONCE APPROVED SO I CAN COORDINATE THE EQUIVALENT CHANGE.
Update the SUSE templates to correct a bug introduced when downloading packages.  
Improve the permissions of the Alpine build to allow the use of the private key when validating  packages signed using the Adoptium private key.

Package Build Fixes Post Release Cycle

---

.github/workflows/wix.yml
wix/Build.OpenJDK_generic.cmd
wix/README.md
wix/SourceDir/CreateSourceFolder.AdoptOpenJDK.ps1

Tested with Microsoft installers, behavior is as expected

Updated default wix version from 5.0.0 to 5.0.2

---

wix/Build.OpenJDK_generic.cmd
wix/BuildSetupTranslationTransform.cmd
wix/README.md

Included in this change:
- allows for MSIs to be made on windows aarch64 machines
- enables users to use a nondefault windows SDK version as long as it is compatible and has the needed tools
This allows users to decouple windows_aarch64 MSI creation from needing windows_x64 machines and binaries for creation. 
Note: All original defaults are preserved.
I have tested these changes through the Microsoft build process, and I have tested the resulting installers to make sure that the same, expected behavior is observed.

Enabled MSI creation on windows_aarch64

---

linux_new/jdk/rhel/src/main/packaging/temurin/24/temurin-24-jdk.template.j2
linux_new/jdk/suse/src/main/packaging/temurin/24/temurin-24-jdk.template.j2
linux_new/jre/rhel/src/main/packaging/temurin/24/temurin-24-jre.template.j2
linux_new/jre/suse/src/main/packaging/temurin/24/temurin-24-jre.template.j2

Update JDK24 installer templates for RPM ( RHEL & SUSE ) based distributions.
Fixes #1008
Also makes the required change for JDK24 ( see issue #1126 )
Changes the default package name to java-24-temurin-jdk, but also creates symlinks to the previous
`temurin-24-jre -> /usr/lib/jvm/java-24-temurin-jre`  
`temurin-24-jdk -> /usr/lib/jvm/java-24-temurin-jdk`  
`java-24-temurin-jdk`  
`java-24-temurin-jre`  
The new JDK/JRE package has this list of provides :  
JDK
```
rpm -q --provides java-24-temurin-jdk
java
java-24
java-24-devel
java-24-headless
java-24-openjdk
java-24-openjdk-devel
java-24-openjdk-headless
java-24-temurin-jdk = 24.0.0.0.0.36-0
java-24-temurin-jdk(x86-64) = 24.0.0.0.0.36-0
java-devel
java-devel-openjdk
java-headless
java-openjdk
java-openjdk-devel
java-openjdk-headless …
```

Update JDK24 RPM installer templates

---

linux_new/jdk/alpine/src/main/packaging/temurin/24/alpine.jdk24.template.j2

Fixes #1146 
There are 2 directories that have been removed from the Alpine JDK build ( the JRE never had these ) , the jmods and the man directories. The APKBuild template file needs amending to also remove these entries.

Remove redundant dirs from JDK24 Alpine build

---

linux_new/Jenkinsfile
linux_new/jdk/rhel/src/main/packaging/temurin/24/temurin-24-jdk.template.j2
linux_new/jdk/suse/src/main/packaging/temurin/24/temurin-24-jdk.template.j2
linux_new/jre/rhel/src/main/packaging/temurin/24/temurin-24-jre.template.j2
linux_new/jre/suse/src/main/packaging/temurin/24/temurin-24-jre.template.j2

Following the PMC discussion, the decision was made to maintain the original temurin RPM file names, but continue to install to an SELinux compatible path, and allow symlinks and virtual provides to work for both new & old install locations and names.

Update JDK24 RPM File Names To Be temurin-24 rather than java-24

---

linux_new/jdk/rhel/src/main/packaging/temurin/24/temurin-24-jdk.template.j2
linux_new/jdk/suse/src/main/packaging/temurin/24/temurin-24-jdk.template.j2
linux_new/jre/rhel/src/main/packaging/temurin/24/temurin-24-jre.template.j2
linux_new/jre/suse/src/main/packaging/temurin/24/temurin-24-jre.template.j2

Fixes #1126  improve the specification of the public library provides, by including the system architecture flag.
Tested build with my local installer build process: [https://ci.adoptium.net/job/build-scripts/job/release/job/sfr-build-linux-package-modular/1025/console](https://ci.adoptium.net/job/build-scripts/job/release/job/sfr-build-linux-package-modular/1025/console)   
and package installs on local vms for Fedora 40, Centos 8 and OpenSuse.

Improve JDK24 RPM Provides

---

linux/README.md
linux/jdk/redhat/src/main/packaging/build.sh
linux/jdk/suse/build.gradle
linux/jdk/suse/src/main/packaging/build.sh
linux/jdk/suse/src/main/packaging/microsoft/11/msopenjdk-11.spec
linux/jdk/suse/src/main/packaging/microsoft/17/msopenjdk-17.spec
linux/jdk/suse/src/main/packaging/microsoft/21/msopenjdk-21.spec
linux/jdk/suse/src/packageTest/java/packaging/SuseFlavours.java
linux/jre/suse/build.gradle
linux/jre/suse/src/main/packaging/build.sh
linux/jre/suse/src/packageTest/java/packaging/SuseFlavours.java
linux_new/README.md
linux_new/jdk/rhel/src/main/packaging/build.sh
linux_new/jdk/suse/build.gradle
linux_new/jdk/suse/src/main/packaging/build.sh
linux_new/jdk/suse/src/packageTest/java/packaging/SuseFlavours.java
linux_new/jre/suse/build.gradle
linux_new/jre/suse/src/main/packaging/build.sh
linux_new/jre/suse/src/packageTest/java/packaging/SuseFlavours.java

Changes tested internally by building MSFT openjdk. Changes made in both `linux` and `linux_new` folders

Enabled Suse RPMs to get built locally

---

linux_new/Jenkinsfile

Fixes #1167 & #1168 
Allow the automated linux installer package build process to skip package types if required during a manual run.
Improve the automated linux installer package build process to skip unsupported platforms ( rather than cause errors ).
Improve the jenkins job description to highlight what a job was triggered for, or skipped for...

Add selective packaging to linux installer process.

---

linux_new/jdk/debian/build.gradle
linux_new/jre/debian/build.gradle

See #1216 
Same fix is now required for s390x & arm32..

Update Debian Installer Build For s390x & arm32 to use debian:bookworm docker image

---

pkgbuild/Jenkinsfile

Update the mac pkg build process to not build installer packages for the mac jmods archive.
Tested In Isolation Here: https://ci.adoptium.net/job/build-scripts/job/release/job/sfr-mac-installer/1/

MAC Pkgbuild Process : Exclude Jmods from PKG build

---

docs/Guide_To_The_Linux_Installers.md
linux/README.md
linux/ca-certificates/debian/build.gradle
linux/ca-certificates/debian/src/packageTest/java/org/adoptium/cacertificates/ChangesVerificationTest.java
linux/ca-certificates/debian/src/packageTest/java/org/adoptium/cacertificates/DebianFlavours.java
linux/jdk/debian/src/packageTest/java/packaging/DebianFlavours.java
linux/jre/debian/src/main/packaging/build.sh
linux/jre/debian/src/packageTest/java/packaging/DebianFlavours.java
linux_new/Jenkinsfile
linux_new/README.md
linux_new/jdk/debian/src/main/packaging/build.sh
linux_new/jdk/debian/src/packageTest/java/packaging/DebianFlavours.java
linux_new/jre/debian/src/main/packaging/build.sh
linux_new/jre/debian/src/packageTest/java/packaging/DebianFlavours.java

Looks like this issue came up again. This PR fixes the installer tool in the same way that I fixed it when debian:buster went eol. Used my other PR as a template: https://github.com/adoptium/installer/pull/1220

Completely removed support for Ubuntu:Oracular due to eol failures

---

linux/ca-certificates/debian/src/main/packaging/debian/control

Fixes issue https://github.com/adoptium/installer/issues/1245

Add Multi-Arch foreign to adoptium-ca-certificates
